Repository palantir/blueprint, pull requests merged in 2018-02, with the labels that each got.

#2117 [datetime] remove moment dependency
  packages/datetime/package.json
  packages/datetime/src/common/dateUtils.ts
  packages/datetime/src/dateFormat.tsx
  packages/datetime/src/dateFormatter.ts
  packages/datetime/src/dateInput.tsx
  packages/datetime/src/datePickerCore.tsx
  packages/datetime/src/dateRangeInput.tsx
  packages/datetime/src/dateinput.md
  packages/datetime/src/index.ts
  packages/datetime/test/common/dateFormat.ts
  packages/datetime/test/common/dateTestUtils.ts
  packages/datetime/test/dateInputTests.tsx
  packages/datetime/test/dateRangeInputTests.tsx
  packages/datetime/test/isotest.js
  packages/docs-app/src/examples/datetime-examples/common/formatSelect.tsx
  packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
Labels: Status: work in progress, Type: breaking change

#2102 [core] add support for more Alert props
  packages/core/src/common/errors.ts
  packages/core/src/components/alert/alert.tsx
  packages/core/test/alert/alertTests.tsx
  packages/docs-app/src/examples/core-examples/alertExample.tsx
Labels: Type: refactor

#2128 reduce build parallelism
  .circleci/config.yml
Labels: Domain: tooling

#2129 headings use pixel values for line-height
  packages/core/src/_typography.scss
Labels: Type: breaking change

#2127 TimezonePicker only controlled usage
  package.json
  packages/docs-app/src/examples/timezone-examples/timezonePickerExample.tsx
  packages/timezone/src/components/timezone-picker/timezoneDisplayFormat.ts
  packages/timezone/src/components/timezone-picker/timezoneItems.ts
  packages/timezone/src/components/timezone-picker/timezoneMetadata.ts
  packages/timezone/src/components/timezone-picker/timezonePicker.tsx
  packages/timezone/src/components/timezone-picker/timezoneUtils.ts
  packages/timezone/test/timezonePickerTests.tsx
Labels: Type: breaking change

#2142 add list of recommended VS Code extensions
  .vscode/extensions.json
Labels: Domain: tooling

#2138 [Dialog] Change dialog header to h4
  packages/core/src/components/dialog/_dialog.scss
  packages/core/src/components/dialog/dialog.tsx
Labels: Type: breaking change
