Repository palantir/blueprint, pull requests merged in 2018-06, with the labels that each got.

#2563 allow retrying OverflowList & Table tests
  packages/core/test/overflow-list/overflowListTests.tsx
  packages/table/test/tableTests.tsx
Labels: Domain: testing

#2570 [core] better FormGroup
  packages/core/src/components/forms/_common.scss
  packages/core/src/components/forms/_controls.scss
  packages/core/src/components/forms/_form-group.scss
  packages/core/src/components/forms/form-group.md
  packages/core/src/components/forms/formGroup.tsx
  packages/core/test/forms/formGroupTests.tsx
  packages/docs-app/src/examples/core-examples/formGroupExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Type: breaking change

#2571 [core] HTML Label component
  packages/core/src/components/forms/_label.scss
  packages/core/src/components/forms/label.md
  packages/core/src/components/forms/label.tsx
  packages/core/src/components/html/html.md
  packages/core/src/components/html/html.tsx
  packages/core/src/components/index.ts
  packages/core/test/forms/labelTests.tsx
  packages/core/test/index.ts
  packages/docs-app/src/examples/core-examples/cardExample.tsx
  packages/docs-app/src/examples/core-examples/checkboxExample.tsx
  packages/docs-app/src/examples/core-examples/collapsibleListExample.tsx
  packages/docs-app/src/examples/core-examples/common/intentSelect.tsx
  packages/docs-app/src/examples/core-examples/iconExample.tsx
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
  packages/docs-app/src/examples/core-examples/overflowListExample.tsx
  packages/docs-app/src/examples/core-examples/popoverExample.tsx
  packages/docs-app/src/examples/core-examples/spinnerExample.tsx
  packages/docs-app/src/examples/core-examples/switchExample.tsx
  packages/docs-app/src/examples/core-examples/toastExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
  packages/docs-app/src/examples/table-examples/columnLoadingExample.tsx
Labels: Type: breaking change

#2576 MultiSlider tests
  packages/core/src/components/slider/handle.tsx
  packages/core/src/components/slider/slider.tsx
  packages/core/test/index.ts
  packages/core/test/slider/handleTests.tsx
  packages/core/test/slider/multiSliderTests.tsx
  packages/core/test/slider/rangeSliderTests.tsx
  packages/core/test/slider/sliderTestUtils.ts
  packages/core/test/slider/sliderTests.tsx
Labels: Type: refactor

#2569 MultiSlider refactors
  packages/core/src/common/classes.ts
  packages/core/src/components/slider/_slider.scss
  packages/core/src/components/slider/multiSlider.tsx
  packages/core/test/slider/multiSliderTests.tsx
  packages/docs-app/src/examples/core-examples/multiSliderExample.tsx
Labels: Type: refactor

#2539 [Core/Datetime] remove usePortal={false} where not documented
  packages/core/src/components/menu/menuItem.tsx
  packages/datetime/src/dateInput.tsx
  packages/datetime/src/dateRangeInput.tsx
  packages/datetime/test/dateInputTests.tsx
  packages/datetime/test/dateRangeInputTests.tsx
Labels: Type: breaking change

#2579 Spinner size prop replaces small/large
  packages/core/src/components/forms/_input-group.scss
  packages/core/src/components/spinner/_common.scss
  packages/core/src/components/spinner/_spinner.scss
  packages/core/src/components/spinner/spinner.md
  packages/core/src/components/spinner/spinner.tsx
  packages/core/test/spinner/spinnerTests.tsx
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/spinnerExample.tsx
Labels: Type: breaking change

#2431 [Tag] Add icon and rightIcon props
  packages/core/src/common/classes.ts
  packages/core/src/components/tag-input/_tag-input.scss
  packages/core/src/components/tag/_common.scss
  packages/core/src/components/tag/_tag.scss
  packages/core/src/components/tag/tag.md
  packages/core/src/components/tag/tag.tsx
  packages/core/src/components/text/text.tsx
  packages/core/test/tag-input/tagInputTests.tsx
  packages/core/test/tag/tagTests.tsx
  packages/docs-app/src/examples/core-examples/tagExample.tsx
  packages/docs-app/src/styles/_examples.scss
Labels: Type: breaking change

#2581 [Overlay] better lifecycle props for all overlay components
  packages/core/src/components/alert/alert.tsx
  packages/core/src/components/context-menu/contextMenu.tsx
  packages/core/src/components/overlay/overlay.tsx
  packages/core/src/components/popover/popover.tsx
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/test/alert/alertTests.tsx
  packages/core/test/dialog/dialogTests.tsx
  packages/core/test/overlay/overlayTests.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/tooltip/tooltipTests.tsx
  packages/datetime/test/dateInputTests.tsx
  packages/datetime/test/dateRangeInputTests.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
  packages/select/src/components/omnibar/omnibar.tsx
  packages/select/src/components/select/multiSelect.tsx
  packages/select/src/components/select/select.tsx
  packages/select/src/components/select/suggest.tsx
  packages/select/test/selectTests.tsx
  packages/select/test/suggestTests.tsx
  packages/table/src/headers/columnHeaderCell.tsx
Labels: Type: breaking change

#2593 use smaller (relative) font-size for `code`
  packages/core/src/_typography.scss
Labels: Domain: design

#2594 [docs] improve button-group docs
  packages/core/src/components/button/_button-group.scss
  packages/core/src/components/button/_button.scss
  packages/core/src/components/button/button-group.md
  packages/core/src/components/button/button.md
  packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
Labels: Domain: documentation

#2601 remove SVGPopover and SVGTooltip as they only set one prop
  packages/core/src/components/popover/svgPopover.tsx
  packages/core/src/components/tooltip/svgTooltip.tsx
  packages/core/test/isotest.js
Labels: Type: breaking change

#2608 TS sourcemaps & fix code coverage reports
  config/tsconfig.base.json
  packages/core/src/accessibility/focusStyleManager.ts
  packages/docs-app/src/tsconfig.json
  packages/karma-build-scripts/createKarmaConfig.js
  packages/karma-build-scripts/package.json
  packages/landing-app/src/tsconfig.json
  yarn.lock
Labels: Domain: tooling

#2606 core Table => HTMLTable for obviousness
  packages/core/src/components/_index.scss
  packages/core/src/components/components.md
  packages/core/src/components/html-table/_html-table.scss
  packages/core/src/components/html-table/html-table.md
  packages/core/src/components/html-table/htmlTable.tsx
  packages/core/src/components/index.ts
  packages/docs-theme/src/components/modifierTable.tsx
Labels: Type: breaking change

#2617 IPopoverSharedProps used by Popover and Tooltip, some prop renames
  packages/core/scripts/upgrade-blueprint-3.0.0-rename.sh
  packages/core/src/components/context-menu/contextMenu.tsx
  packages/core/src/components/index.ts
  packages/core/src/components/popover/popover.tsx
  packages/core/src/components/popover/popoverSharedProps.tsx
  packages/core/src/components/tooltip/tooltip.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/tooltip/tooltipTests.tsx
Labels: Type: breaking change

#2622 [OverflowList] Recalculate visible items when modifying collapseFrom
  packages/core/src/components/overflow-list/overflowList.tsx
Labels: Package: core
