Repository palantir/blueprint, pull requests merged in 2018-12, with the labels that each got.

#3206 Update codesandbox URL
  README.md
  packages/docs-app/src/components/welcome.tsx
Labels: Domain: documentation

#3209 Circle bot logs artifact URLs if auth token is missing
  package.json
  scripts/preview.js
  yarn.lock
Labels: Domain: tooling

#3222 [Icons] Added new icons
  packages/icons/resources/icons/icons-16.eot
  packages/icons/resources/icons/icons-16.ttf
  packages/icons/resources/icons/icons-16.woff
  packages/icons/resources/icons/icons-20.eot
  packages/icons/resources/icons/icons-20.ttf
  packages/icons/resources/icons/icons-20.woff
  packages/icons/resources/icons/icons.json
  resources/icons/16px/cube-add.svg
  resources/icons/16px/cube-remove.svg
  resources/icons/16px/cube.svg
  resources/icons/16px/lifesaver.svg
  resources/icons/16px/th-filtered.svg
  resources/icons/20px/cube-add.svg
  resources/icons/20px/cube-remove.svg
  resources/icons/20px/cube.svg
  resources/icons/20px/lifesaver.svg
  resources/icons/20px/th-filtered.svg
Labels: Package: icons

#3217 update contributing notes: DO NOT enable Circle for forks.
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Domain: tooling
