Repository palantir/blueprint, pull requests merged in 2018-11, with the labels that each got.

#3119 add isotest for className prop
  packages/core/test/isotest.js
  packages/datetime/test/isotest.js
  packages/icons/test/isotest.js
  packages/select/test/isotest.js
  packages/table/test/isotest.js
  packages/test-commons/src/generateIsomorphicTests.ts
  packages/timezone/test/isotest.js
Labels: Domain: testing, Type: refactor

#3052 [Icons] Added new icon
  packages/icons/resources/icons/icons-16.eot
  packages/icons/resources/icons/icons-16.ttf
  packages/icons/resources/icons/icons-16.woff
  packages/icons/resources/icons/icons-20.eot
  packages/icons/resources/icons/icons-20.ttf
  packages/icons/resources/icons/icons-20.woff
  packages/icons/resources/icons/icons.json
  resources/icons/16px/clean.svg
  resources/icons/20px/clean.svg
Labels: Package: icons

#3161 docs edits
  packages/docs-app/src/blueprint.md
  packages/docs-app/src/whats-new-3.0.md
  packages/select/src/components/select/select-component.md
Labels: Domain: documentation

#3159 🔧 ts-lint --fix
  packages/node-build-scripts/ts-lint.js
Labels: Domain: tooling
