Repository palantir/blueprint, pull requests merged in 2018-07, with the labels that each got.

#2656 [core] merge _reset.scss files
  packages/core/src/_reset.scss
  packages/core/src/blueprint.scss
  packages/core/src/common/_resets.scss
Labels: Type: refactor

#2665 upgrade to TypeScript 2.8
  package.json
  packages/core/package.json
  packages/core/src/components/html-select/htmlSelect.tsx
  packages/datetime/package.json
  packages/docs-theme/package.json
  packages/icons/package.json
  packages/labs/package.json
  packages/node-build-scripts/package.json
  packages/select/package.json
  packages/table/package.json
  packages/test-commons/package.json
  packages/timezone/package.json
  yarn.lock
Labels: Domain: tooling

#2675 [1.x] New notifications icon added
  packages/core/resources/icons/icons-16.eot
  packages/core/resources/icons/icons-16.ttf
  packages/core/resources/icons/icons-16.woff
  packages/core/resources/icons/icons-20.eot
  packages/core/resources/icons/icons-20.ttf
  packages/core/resources/icons/icons-20.woff
  packages/core/resources/icons/icons.json
  resources/icons/16px/pt-icon-notifications-updated.svg
  resources/icons/20px/pt-icon-notifications-updated.svg
Labels: Package: icons

#2621 [OverflowList] Fix order of overflow items
  packages/core/src/components/overflow-list/overflowList.tsx
  packages/core/test/overflow-list/overflowListTests.tsx
  packages/docs-app/src/examples/core-examples/overflowListExample.tsx
Labels: Package: core

#2623 [OverflowList] Add minimum visible items prop
  packages/core/src/components/overflow-list/overflowList.tsx
  packages/core/test/overflow-list/overflowListTests.tsx
Labels: Package: core

#2674 [Icons] New notifications icon added
  packages/icons/resources/icons/icons-16.eot
  packages/icons/resources/icons/icons-16.ttf
  packages/icons/resources/icons/icons-16.woff
  packages/icons/resources/icons/icons-20.eot
  packages/icons/resources/icons/icons-20.ttf
  packages/icons/resources/icons/icons-20.woff
  packages/icons/resources/icons/icons.json
  resources/icons/16px/notifications-updated.svg
  resources/icons/20px/notifications-updated.svg
Labels: Package: icons

#2707 [core] use IOptionProps instead of IHTMLOptionProps
  packages/core/src/common/props.ts
  packages/core/src/components/forms/radioGroup.tsx
  packages/core/src/components/html-select/htmlSelect.tsx
  packages/core/test/controls/radioGroupTests.tsx
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
Labels: Type: refactor

#2709 [Checkbox] inline SVG background-image for icon
  packages/core/package.json
  packages/core/scripts/sass-inline-svg.js
  packages/core/src/components/forms/_controls.scss
  packages/core/src/components/forms/controls.tsx
  packages/core/test/controls/controlsTests.tsx
  yarn.lock
Labels: Type: refactor

#2710 🔧 external source maps in css-dist
  packages/node-build-scripts/css-dist.sh
Labels: Domain: tooling

#2719 [PanelStack] merge some files
  packages/core/src/components/index.ts
  packages/core/src/components/panel-stack/panelHeader.tsx
  packages/core/src/components/panel-stack/panelProps.ts
  packages/core/src/components/panel-stack/panelStack.tsx
  packages/core/src/components/panel-stack/panelView.tsx
  packages/docs-app/src/examples/core-examples/panelStackExample.tsx
Labels: Type: refactor

#2721 [Checkbox] refactor indicators style
  packages/core/src/components/forms/_controls.scss
Labels: Type: refactor

#2729 [webpack-build-scripts] put assets in assets/ dir, preserve filenames
  packages/webpack-build-scripts/webpack.config.base.js
Labels: Domain: tooling

#2738 [PanelStack] use IPanel in openPanel() public API
  packages/core/src/components/panel-stack/panelProps.ts
  packages/core/src/components/panel-stack/panelStack.tsx
  packages/core/src/components/panel-stack/panelView.tsx
  packages/core/test/panel-stack/panelStackTests.tsx
  packages/docs-app/src/examples/core-examples/panelStackExample.tsx
Labels: Type: refactor

#2737 [PanelStack] documentation
  packages/core/src/components/panel-stack/panel-stack.md
  packages/core/src/components/panel-stack/panelProps.ts
  packages/docs-theme/src/styles/_props.scss
Labels: Domain: documentation

#2742 [Breadcrumbs] inline SVG icons
  packages/core/scripts/sass-inline-svg.js
  packages/core/src/components/breadcrumbs/_breadcrumbs.scss
  packages/core/src/components/forms/_controls.scss
Labels: Type: refactor
