Repository palantir/blueprint, pull requests merged in 2018-09, with the labels that each got.

#2908 🔧 switch to tree-sitter-typescript
  package.json
  packages/docs-data/docsUtils.js
  packages/docs-data/package.json
  packages/docs-theme/src/styles/_syntax.scss
  yarn.lock
Labels: Domain: tooling

#2907 🔧 switch to circle-github-bot
  .circleci/config.yml
  package.json
  scripts/artifact-variables
  scripts/preview.js
  scripts/submit-preview-comment
  yarn.lock
Labels: Domain: tooling

#2914 [Collapse] refactor docs
  packages/core/src/components/collapse/collapse.tsx
Labels: Type: refactor

#2915 🔧 bump sass-inline-svg
  packages/core/package.json
  yarn.lock
Labels: Domain: tooling

#2917 [select] update docs for other resetOnX props
  packages/select/src/common/listItemsProps.ts
  packages/select/src/components/select/select.tsx
Labels: Domain: documentation

#2916 [select] QueryList reset followups
  packages/docs-app/src/examples/select-examples/omnibarExample.tsx
  packages/select/src/components/query-list/queryList.tsx
  packages/select/test/queryListTests.tsx
  packages/select/test/selectComponentSuite.tsx
Labels: Type: refactor

#2970 [Spinner] prevent track overflow
  packages/core/src/components/spinner/spinner.tsx
  packages/core/test/spinner/spinnerTests.tsx
Labels: Type: refactor

#2967 [Icons] New icons added
  packages/icons/resources/icons/icons-16.eot
  packages/icons/resources/icons/icons-16.ttf
  packages/icons/resources/icons/icons-16.woff
  packages/icons/resources/icons/icons-20.eot
  packages/icons/resources/icons/icons-20.ttf
  packages/icons/resources/icons/icons-20.woff
  packages/icons/resources/icons/icons.json
  resources/icons/16px/flow-branch.svg
  resources/icons/16px/flow-end.svg
  resources/icons/16px/flow-linear.svg
  resources/icons/16px/flow-review-branch.svg
  resources/icons/16px/flow-review.svg
  resources/icons/16px/list-columns.svg
  resources/icons/20px/flow-branch.svg
  resources/icons/20px/flow-end.svg
  resources/icons/20px/flow-linear.svg
  resources/icons/20px/flow-review-branch.svg
  resources/icons/20px/flow-review.svg
  resources/icons/20px/list-columns.svg
Labels: Package: icons

#2968 [1.x] New icons added
  packages/core/resources/icons/icons-16.eot
  packages/core/resources/icons/icons-16.ttf
  packages/core/resources/icons/icons-16.woff
  packages/core/resources/icons/icons-20.eot
  packages/core/resources/icons/icons-20.ttf
  packages/core/resources/icons/icons-20.woff
  packages/core/resources/icons/icons.json
  resources/icons/16px/pt-icon-flow-branch.svg
  resources/icons/16px/pt-icon-flow-end.svg
  resources/icons/16px/pt-icon-flow-linear.svg
  resources/icons/16px/pt-icon-flow-review-branch.svg
  resources/icons/16px/pt-icon-flow-review.svg
  resources/icons/16px/pt-icon-list-columns.svg
  resources/icons/20px/pt-icon-flow-branch.svg
  resources/icons/20px/pt-icon-flow-end.svg
  resources/icons/20px/pt-icon-flow-linear.svg
  resources/icons/20px/pt-icon-flow-review-branch.svg
  resources/icons/20px/pt-icon-flow-review.svg
  resources/icons/20px/pt-icon-list-columns.svg
Labels: Package: icons

#2981 [OverflowLists] refactor tests to use a sweet harness
  packages/core/test/overflow-list/overflowListTests.tsx
Labels: Domain: testing, Type: refactor
