Repository palantir/blueprint, pull requests merged in 2023-10, with the labels that each got.

#6250 [core] feat: SwitchCard component
  packages/core/src/common/_variables-extended.scss
  packages/core/src/common/classes.ts
  packages/core/src/components/_index.scss
  packages/core/src/components/card-list/card-list.scss
  packages/core/src/components/card-list/cardList.tsx
  packages/core/src/components/card/_card-variables.scss
  packages/core/src/components/card/_card.scss
  packages/core/src/components/card/card.md
  packages/core/src/components/components.md
  packages/core/src/components/control-card/_control-card.scss
  packages/core/src/components/control-card/control-card.md
  packages/core/src/components/control-card/controlCard.tsx
  packages/core/src/components/control-card/switchCard.tsx
  packages/core/src/components/forms/controls.tsx
  packages/core/src/components/index.ts
  packages/core/test/control-card/controlCardTests.tsx
  packages/core/test/index.ts
  packages/docs-app/src/examples/core-examples/controlCardListExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/examples/core-examples/switchCardExample.tsx
  packages/docs-app/src/styles/_examples.scss
Labels: Type: feature request, Package: core

#6436 chore: upgrade build dependencies
  lerna.json
  nx.json
  package.json
  packages/docs-app/package.json
  packages/eslint-config/package.json
  packages/eslint-plugin/package.json
  packages/node-build-scripts/package.json
  yarn.lock
Labels: Domain: tooling

#6438 [demo-app] fix: load blueprint-datetime2.css
  packages/demo-app/package.json
  packages/demo-app/src/index.scss
Labels: Type: bug

#6431 [icons] feat: new icons "geotime" and "unlink"
  packages/icons/icons.json
  resources/icons/16px/geotime.svg
  resources/icons/16px/unlink.svg
  resources/icons/20px/geotime.svg
  resources/icons/20px/unlink.svg
Labels: Type: feature request, Package: icons

#6343 [core] fix(Input): Mute input shadows
  packages/core/src/common/_variables.scss
Labels: Status: in discussion, Package: core, Domain: design

#6461 docs: add 'deprecated' tag to nav menu items
  packages/core/src/components/panel-stack/panel-stack.md
  packages/core/src/legacy/hotkeys-legacy.md
  packages/datetime/src/components/date-input/date-input.md
  packages/datetime/src/components/date-picker/datepicker.md
  packages/datetime/src/components/date-range-input/date-range-input.md
  packages/datetime/src/components/date-range-picker/daterangepicker.md
  packages/docs-app/src/components/blueprintDocs.tsx
Labels: Domain: documentation

#6474 [eslint-plugin] feat: no-deprecated-popover2-components rule
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/no-deprecated-components/createNoDeprecatedComponentsRule.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/index.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-components.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-popover2-components.ts
  packages/eslint-plugin/test/no-deprecated-popover2-components.test.ts
Labels: Domain: tooling

#6479 [eslint-plugin] feat(no-deprecated-table-components): lint V2 APIs
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-table-components.ts
  packages/eslint-plugin/test/no-deprecated-table-components.test.ts
Labels: Domain: tooling
