Repository palantir/blueprint, pull requests merged in 2023-01, with the labels that each got.

#5807 feat(MenuItem, MenuItem2): roleStructure="listitem"
  packages/core/src/components/menu/menuItem.tsx
  packages/core/test/menu/menuItemTests.tsx
  packages/popover2/src/menu-item2.md
  packages/popover2/src/menuItem2.tsx
  packages/popover2/test/menuItem2Tests.tsx
Labels: Status: waiting on author

#5806 [select] fix(Suggest2): show non-empty query when popover closed
  packages/select/src/components/suggest/suggest2.tsx
Labels: Type: bug

#5850 docs: fix callout heading markup
  packages/core/src/components/breadcrumbs/breadcrumbs.md
  packages/core/src/components/button/button.md
  packages/core/src/components/collapsible-list/collapsible-list.md
  packages/core/src/components/context-menu/context-menu.md
  packages/core/src/components/dialog/dialog.md
  packages/core/src/components/editable-text/editable-text.md
  packages/core/src/components/forms/control-group.md
  packages/core/src/components/forms/file-input.md
  packages/core/src/components/forms/label.md
  packages/core/src/components/forms/text-inputs.md
  packages/core/src/components/hotkeys/hotkeys-target2.md
  packages/core/src/components/hotkeys/hotkeys.md
  packages/core/src/components/html-table/html-table.md
  packages/core/src/components/icon/icon.md
  packages/core/src/components/menu/menu.md
  packages/core/src/components/navbar/navbar.md
  packages/core/src/components/non-ideal-state/non-ideal-state.md
  packages/core/src/components/overlay/overlay.md
  packages/core/src/components/panel-stack/panel-stack.md
  packages/core/src/components/panel-stack2/panel-stack2.md
  packages/core/src/components/popover/popover.md
  packages/core/src/components/portal/portal.md
  packages/core/src/components/resize-sensor/resize-sensor.md
  packages/core/src/components/skeleton/skeleton.md
  packages/core/src/components/spinner/spinner.md
  packages/core/src/components/tag-input/tag-input.md
  packages/core/src/components/toast/toast.md
  packages/core/src/components/tooltip/tooltip.md
  packages/core/src/context/hotkeys/hotkeys-provider.md
  packages/core/src/hooks/hotkeys/use-hotkeys.md
  packages/datetime/src/dateinput.md
  packages/datetime/src/daterangeinput.md
  packages/datetime/src/datetimepicker.md
  packages/datetime2/src/components/date-input2/date-input2.md
  packages/datetime2/src/components/date-range-input2/date-range-input2.md
  packages/datetime2/src/components/timezone-select/timezone-select.md
  packages/datetime2/src/index.md
  packages/docs-app/src/blueprint.md
  packages/docs-app/src/getting-started.md
  packages/popover2/src/breadcrumbs2.md
  packages/popover2/src/context-menu2.md
  packages/popover2/src/menu-item2.md
  packages/popover2/src/popover2.md
  packages/popover2/src/resize-sensor2.md
  packages/popover2/src/tooltip2.md
  packages/select/src/components/multi-select/multi-select.md
  packages/select/src/components/multi-select/multi-select2.md
  packages/select/src/components/select/select-component.md
  packages/select/src/components/select/select2.md
  packages/select/src/components/suggest/suggest.md
  packages/select/src/components/suggest/suggest2.md
  packages/table/src/docs/table-api.md
  packages/table/src/docs/table-features.md
  packages/table/src/docs/table.md
  packages/timezone/src/components/timezone-picker/timezone-picker.md
Labels: Domain: documentation
