Repository palantir/blueprint, pull requests merged in 2023-08, with the labels that each got.

#6312 [core] add AsyncControllableTextArea based on AsyncControllableInput & add async control option for TextArea component
  packages/core/src/components/forms/asyncControllableTextArea.tsx
  packages/core/src/components/forms/textArea.tsx
  packages/core/src/components/forms/useAsyncControllableValue.ts
  packages/core/test/forms/asyncControllableInputTests.tsx
Labels: Type: enhancement, Package: core

#6336 chore: fix dependabot configuration syntax
  .github/dependabot.yml
Labels: Domain: tooling

#6337 docs: use latest code sandbox link everywhere
  .github/ISSUE_TEMPLATE/Bug_report.md
  README.md
  packages/docs-app/src/components/welcome.tsx
Labels: Domain: documentation
