Repository palantir/blueprint, pull requests merged in 2023-11, with the labels that each got.

#6521 Use `React.FC` for PanelStack2 `renderPanel` typing to fix compilation on newer `@types/react` versions
  packages/core/src/components/panel-stack2/panelTypes.ts
Labels: Type: bug, Status: in discussion

#6531 [docs-app] feat: use SegmentedControl across examples
  packages/docs-app/src/examples/core-examples/buttonsExample.tsx
  packages/docs-app/src/examples/core-examples/cardExample.tsx
  packages/docs-app/src/examples/core-examples/common/alignmentSelect.tsx
  packages/docs-app/src/examples/core-examples/common/booleanOrUndefinedSelect.tsx
  packages/docs-app/src/examples/core-examples/common/intentSelect.tsx
  packages/docs-app/src/examples/core-examples/common/layoutSelect.tsx
  packages/docs-app/src/examples/core-examples/common/sizeSelect.tsx
  packages/docs-app/src/examples/core-examples/drawerExample.tsx
  packages/docs-app/src/examples/core-examples/formGroupExample.tsx
  packages/docs-app/src/examples/core-examples/htmlSelectExample.tsx
  packages/docs-app/src/examples/core-examples/menuItemExample.tsx
  packages/docs-app/src/examples/core-examples/multistepDialogExample.tsx
  packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
  packages/docs-app/src/examples/core-examples/popoverExample.tsx
  packages/docs-app/src/examples/core-examples/sectionExample.tsx
  packages/docs-app/src/examples/core-examples/segmentedControlExample.tsx
  packages/docs-app/src/examples/core-examples/switchCardExample.tsx
  packages/docs-app/src/examples/core-examples/switchExample.tsx
  packages/docs-app/src/examples/core-examples/tagInputExample.tsx
  packages/docs-app/src/examples/core-examples/toastExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
  packages/docs-app/src/examples/datetime2-examples/common/minMaxDateSelect.tsx
  packages/docs-app/src/examples/table-examples/columnLoadingExample.tsx
Labels: Domain: documentation

#6538 chore: migrate to @twbs/fantasticon
  .github/dependabot.yml
  packages/icons/package.json
  packages/icons/scripts/generate-icon-fonts.mjs
  yarn.lock
Labels: Domain: tooling, Package: icons

#6506 [core] feat(Section): a11y improvements, titleRenderer prop
  packages/core/src/components/section/section.tsx
  packages/core/test/section/sectionTests.tsx
Labels: Type: enhancement, P2, Package: core, Domain: accessibility

#6552 [docs-app] feat: add intent options for InputGroup, TextArea
  packages/core/src/components/forms/input-group.md
  packages/core/src/components/forms/text-area.md
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/textAreaExample.tsx
Labels: Domain: documentation

#6551 [node-build-scripts] fix(es-lint): await formatter results correctly
  packages/eslint-config/index.js
  packages/node-build-scripts/css-dist.mjs
  packages/node-build-scripts/es-lint.mjs
  packages/node-build-scripts/generate-css-variables.mjs
  packages/node-build-scripts/sass-compile.mjs
  packages/node-build-scripts/sass-lint.mjs
  packages/node-build-scripts/src/sass/sassCompileFile.mjs
Labels: Domain: tooling

#6555 chore: upgrade to Nx v17, migrate away from `lerna run`
  .circleci/config.yml
  .gitignore
  README.md
  nx.json
  package.json
  packages/docs-data/package.json
  yarn.lock
Labels: Domain: tooling

#6562 chore: fix npm auth setting for Yarn
  scripts/publish-npm-semver-tagged
Labels: Domain: tooling

#6563 [node-build-scripts] fix(sass-compile, css-dist): add shebang
  packages/node-build-scripts/css-dist.mjs
  packages/node-build-scripts/sass-compile.mjs
Labels: Domain: tooling

#6573 [icons] feat: new icons "group", "input"
  packages/icons/icons.json
  resources/icons/16px/group-item.svg
  resources/icons/16px/input.svg
  resources/icons/20px/group-item.svg
  resources/icons/20px/input.svg
Labels: Status: in discussion
