Repository palantir/blueprint, pull requests merged in 2024-12, with the labels that each got.

#7109 [docs] Update CardListExample
  packages/docs-app/src/examples/core-examples/cardListExample.tsx
Labels: Domain: documentation

#7110 [docs] Update Control Card Examples
  packages/docs-app/src/examples/core-examples/checkboxCardExample.tsx
  packages/docs-app/src/examples/core-examples/checkboxExample.tsx
  packages/docs-app/src/examples/core-examples/controlCardListExample.tsx
  packages/docs-app/src/examples/core-examples/radioCardGroupExample.tsx
  packages/docs-app/src/examples/core-examples/radioExample.tsx
  packages/docs-app/src/examples/core-examples/switchCardExample.tsx
  packages/docs-app/src/examples/core-examples/switchExample.tsx
Labels: Domain: documentation

#7037 feat(Table2) Row focus mode
  packages/table-dev-app/src/mutableTable.tsx
  packages/table/src/common/cellTypes.ts
  packages/table/src/common/internal/focusedCellUtils.ts
  packages/table/src/common/internal/selectionUtils.ts
  packages/table/src/headers/header.tsx
  packages/table/src/interactions/reorderable.tsx
  packages/table/src/interactions/selectable.tsx
  packages/table/src/regions.ts
  packages/table/src/table.tsx
  packages/table/src/table2.tsx
  packages/table/src/table2Utils.ts
  packages/table/src/tableBody.tsx
  packages/table/src/tableBody2.tsx
  packages/table/src/tableBodyCells.tsx
  packages/table/src/tableHotkeys.ts
  packages/table/src/tableProps.ts
  packages/table/src/tableState.ts
  packages/table/test/common/internal/focusedCellUtilsTests.ts
  packages/table/test/common/internal/selectionUtilsTests.ts
  packages/table/test/reorderableTests.tsx
  packages/table/test/selectableTests.tsx
  packages/table/test/table2Tests.tsx
  packages/table/test/tableBody2Tests.tsx
  packages/table/test/tableBodyTests.tsx
Labels: no changelog

#7108 [docs] Update CardExample
  packages/docs-app/src/examples/core-examples/cardExample.tsx
Labels: Domain: documentation

#7111 [docs] Rewrite Card docs
  packages/core/src/components/breadcrumbs/breadcrumbs.md
  packages/core/src/components/button/button-group.md
  packages/core/src/components/button/buttons.md
  packages/core/src/components/callout/callout.md
  packages/core/src/components/card/card.md
  packages/docs-app/src/examples/core-examples/breadcrumbsExamples.tsx
  packages/docs-app/src/examples/core-examples/cardExamples.tsx
  packages/docs-app/src/examples/core-examples/cardPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation

#7116 fix(AnchorButton) Fix missing default tab index
  packages/core/src/accessibility/useInteractiveAttributes.ts
  packages/core/src/components/button/buttons.tsx
Labels: no changelog

#7106 Update button tests to use RTL
  packages/core/package.json
  packages/core/test/buttons/buttonTests.tsx
  yarn.lock
Labels: Domain: testing

#7112 [docs] Rewrite CardList docs
  packages/core/src/components/card-list/card-list.md
  packages/docs-app/src/examples/core-examples/cardListExamples.tsx
  packages/docs-app/src/examples/core-examples/cardListPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation

#7122 fix(DateInput3): Fix wrong today date for timezone mismatch
  packages/datetime2/karma.conf.js
  packages/datetime2/src/components/date-input3/dateInput3.tsx
  packages/datetime2/src/components/date-picker3/datePicker3.tsx
  packages/datetime2/src/components/date-picker3/datePicker3Props.ts
  packages/datetime2/test/components/datePicker3Tests.tsx
Labels: no changelog

#7123 [docs] Rewrite Collapse docs
  packages/core/src/components/collapse/collapse.md
  packages/docs-app/src/examples/core-examples/collapseExample.tsx
  packages/docs-app/src/examples/core-examples/collapseExamples.tsx
  packages/docs-app/src/examples/core-examples/collapsePlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation

#7124 [docs] Rewrite Divider docs
  packages/core/src/components/divider/divider.md
  packages/docs-app/src/examples/core-examples/dividerExample.tsx
  packages/docs-app/src/examples/core-examples/dividerExamples.tsx
  packages/docs-app/src/examples/core-examples/dividerPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation

#7119 add source icon
  packages/icons/icons.json
  resources/icons/16px/data-cloud.svg
  resources/icons/20px/data-cloud.svg
Labels: Package: icons
