Repository palantir/blueprint, pull requests merged in 2024-11, with the labels that each got.

#6711 [core] feat: darken dark theme colors
  packages/core/src/common/_color-aliases.scss
  packages/core/src/common/_typography-colors.scss
  packages/core/src/common/classes.ts
  packages/core/src/components/button/_common.scss
  packages/core/src/components/card-list/card-list.scss
  packages/core/src/components/drawer/_drawer.scss
  packages/core/src/components/panel-stack2/panelView2.tsx
  packages/core/src/components/segmented-control/_segmented-control.scss
  packages/core/src/components/tag/_common.scss
  packages/core/src/components/tag/_compound-tag.scss
  packages/core/src/components/toast/_toast.scss
  packages/demo-app/src/styles/_examples.scss
  packages/docs-app/src/examples/core-examples/buttonPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/checkboxExample.tsx
  packages/docs-app/src/examples/core-examples/formGroupExample.tsx
  packages/docs-app/src/examples/core-examples/progressExample.tsx
  packages/docs-app/src/examples/core-examples/radioExample.tsx
  packages/docs-app/src/examples/core-examples/sectionExample.tsx
  packages/docs-app/src/examples/core-examples/sliderExample.tsx
  packages/docs-app/src/examples/core-examples/spinnerExample.tsx
  packages/docs-app/src/examples/core-examples/switchExample.tsx
  packages/docs-app/src/examples/core-examples/tabsExample.tsx
  packages/docs-app/src/examples/core-examples/treeExample.tsx
  packages/docs-app/src/examples/select-examples/omnibarExample.tsx
  packages/docs-app/src/styles/_examples.scss
  packages/docs-theme/src/components/documentation.tsx
  packages/docs-theme/src/components/navigator.tsx
  packages/docs-theme/src/styles/_variables.scss
  packages/select/src/components/omnibar/_omnibar.scss
Labels: Package: core, Domain: design, do not merge

#7087 [docs] Update AlertExample
  packages/docs-app/src/examples/core-examples/alertExample.tsx
Labels: Domain: documentation

#7088 [docs] Update BreadcrumbsExample
  packages/core/src/components/breadcrumbs/breadcrumbs.md
  packages/docs-app/src/examples/core-examples/breadcrumbsExample.tsx
Labels: Domain: documentation

#7089 [docs] Update ButtonGroupExample
  packages/docs-app/src/examples/core-examples/buttonGroupExample.tsx
Labels: Domain: documentation

#7095 [docs] Rewrite ButtonGroup docs
  packages/core/src/components/button/button-group.md
  packages/docs-app/src/examples/core-examples/buttonExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation

#7078 Update Stylelint to 16.10.0
  .stylelintrc
  package.json
  packages/core/src/common/_mixins.scss
  packages/core/src/components/dialog/_multistep-dialog.scss
  packages/core/src/components/icon/_icon.scss
  packages/core/src/components/spinner/_spinner.scss
  packages/core/src/components/tabs/_tabs.scss
  packages/datetime/src/components/date-range-picker/_daterangepicker.scss
  packages/datetime2/src/components/date-picker3/_date-picker3.scss
  packages/datetime2/src/components/date-range-picker3/_date-range-picker3.scss
  packages/docs-app/src/styles/_examples.scss
  packages/docs-theme/src/styles/_examples.scss
  packages/node-build-scripts/package.json
  packages/stylelint-plugin/package.json
  packages/stylelint-plugin/src/index.ts
  packages/table-dev-app/src/index.scss
  packages/table/src/cell/_cell.scss
  packages/table/src/headers/_headers.scss
  packages/table/src/layers/_layers.scss
  packages/table/src/quadrants/_quadrants.scss
  yarn.lock
Labels: no changelog

#7099 [docs] Rewrite Callout docs
  packages/core/src/components/callout/callout.md
  packages/docs-app/src/examples/core-examples/calloutExamples.tsx
  packages/docs-app/src/examples/core-examples/calloutPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: documentation
