Repository palantir/blueprint, pull requests merged in 2024-05, with the labels that each got.

#6783 [core] fix: toasters closing immediately on hover if `timeout` is set to 0
  packages/core/src/components/toast/toast2.tsx
Labels: no changelog

#6784 [core] style: comment why start/clear timeout handlers are attached to mouse events
  packages/core/src/components/toast/toast2.tsx
Labels: no changelog

#6785 [core] refactor: Use `isTimeoutEnabled` constant in other parts of `<Toast2>`
  packages/core/src/components/toast/toast2.tsx
Labels: no changelog

#6793 chore: reduce Webpack log noise due to missing source maps in external deps
  packages/webpack-build-scripts/webpack.config.base.mjs
  packages/webpack-build-scripts/webpack.config.karma.mjs
Labels: no changelog

#6811 [core] fix: do not colour FormGroup sub label based on intent
  packages/core/changelog/@unreleased/pr-6811.v2.yml
  packages/core/src/components/forms/_form-group.scss
  packages/core/src/components/forms/formGroup.tsx
Labels: Domain: design

#6810 [core] fix: FormGroup sub label dark theme
  packages/core/changelog/@unreleased/pr-6810.v2.yml
  packages/core/src/components/forms/_form-group.scss
Labels: Domain: design

#6751 chore: remove datetime package dependencies to lodash
  packages/datetime/package.json
  packages/datetime/src/common/getTimezone.ts
  packages/datetime/src/common/timezoneUtils.ts
  packages/datetime2/package.json
  yarn.lock
Labels: Status: waiting on author

#6834 use gap instead of margin for tab
  packages/core/src/components/tabs/_tabs.scss
Labels: no changelog

#6803 Avoid trapping focus in Table
  packages/table/src/tableHotkeys.ts
Labels: Domain: accessibility
