Repository palantir/blueprint, pull requests merged in 2025-03, with the labels that each got.

#7288 fix(InputGroup, NumericInput): Add back compat for size prop
  packages/core/src/common/classes.ts
  packages/core/src/components/forms/inputGroup.tsx
  packages/core/src/components/forms/numericInput.tsx
Labels: no changelog

#7301 [DialogBody] Set missing `useOverflowScrollContainer` default prop
  packages/core/src/components/dialog/dialogBody.tsx
Labels: Type: bug, Package: core, no changelog

#7307 fix: enum export
  packages/core/karma.conf.js
  packages/core/src/common/index.ts
Labels: no changelog

#7309 Remove component API console deprecation warnings
  packages/core/src/components/button/buttonGroup.tsx
  packages/core/src/components/button/buttons.tsx
  packages/core/src/components/forms/controls.tsx
  packages/core/src/components/forms/fileInput.tsx
  packages/core/src/components/forms/inputGroup.tsx
  packages/core/src/components/forms/numericInput.tsx
  packages/core/src/components/forms/textArea.tsx
  packages/core/src/components/menu/menu.tsx
  packages/core/src/components/segmented-control/segmentedControl.tsx
  packages/core/src/components/tabs/tabs.tsx
  packages/core/src/components/tag-input/tagInput.tsx
  packages/core/src/components/tag/compoundTag.tsx
  packages/core/src/components/tag/tag.tsx
Labels: no changelog

#7311 break(InputGroup, NumericInput): Remove numeric types for size prop
  packages/core/src/common/classes.ts
  packages/core/src/components/forms/inputGroup.tsx
  packages/core/src/components/forms/numericInput.tsx
Labels: Type: breaking change, no changelog

#7314 break(Overlay): Delete Overlay component
  packages/core/src/components/components.md
  packages/core/src/components/index.ts
  packages/core/src/components/overlay/overlay.md
  packages/core/src/components/overlay/overlay.tsx
  packages/core/src/components/overlay2/overlay2.md
  packages/core/test/index.ts
  packages/core/test/overlay/overlayTests.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/examples/core-examples/overlayExample.tsx
  packages/docs-app/src/styles/_examples.scss
Labels: Type: breaking change, no changelog

#7315 break(Icon): Delete iconSize prop
  packages/core/src/components/icon/icon.tsx
Labels: Type: breaking change, no changelog

#7319 break: Remove deprecated type aliases
  packages/core/karma.conf.js
  packages/core/src/common/index.ts
  packages/core/src/common/props.ts
  packages/core/src/deprecatedTypeAliases.ts
  packages/core/src/index.ts
  packages/core/test/isotest.mjs
Labels: Type: breaking change, no changelog

#7313 break(PanelStack): Delete PanelStack component
  packages/core/src/common/classes.ts
  packages/core/src/common/errors.ts
  packages/core/src/components/_index.scss
  packages/core/src/components/components.md
  packages/core/src/components/index.ts
  packages/core/src/components/panel-stack/_panel-stack.scss
  packages/core/src/components/panel-stack/panel-stack.md
  packages/core/src/components/panel-stack/panelProps.ts
  packages/core/src/components/panel-stack/panelStack.tsx
  packages/core/src/components/panel-stack/panelView.tsx
  packages/core/src/components/panel-stack2/panel-stack2.md
  packages/core/test/index.ts
  packages/core/test/panel-stack/panelStackTests.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/examples/core-examples/panelStackExample.tsx
  packages/docs-app/src/styles/_examples.scss
Labels: Type: breaking change, no changelog

#7322 break(Table): Delete deprecated type aliases
  packages/table/karma.conf.js
  packages/table/src/deprecatedAliases.ts
  packages/table/src/index.ts
Labels: Type: breaking change, no changelog

#7321 break(Table): Delete Table component
  packages/table/karma.conf.js
  packages/table/src/cell/editableCell.tsx
  packages/table/src/common/classes.ts
  packages/table/src/common/contextMenuTargetWrapper.tsx
  packages/table/src/common/errors.ts
  packages/table/src/index.ts
  packages/table/src/quadrants/tableQuadrantStack.tsx
  packages/table/src/table.tsx
  packages/table/src/tableBody.tsx
  packages/table/test/editableCellTests.tsx
  packages/table/test/index.ts
  packages/table/test/mocks/table.tsx
  packages/table/test/tableBodyTests.tsx
  packages/table/test/tableTests.tsx
Labels: Type: breaking change, no changelog

#7328 break(Table2): Rename to Table
  packages/demo-app/src/examples/TableExample.tsx
  packages/docs-app/src/examples/table-examples/cellLoadingExample.tsx
  packages/docs-app/src/examples/table-examples/columnLoadingExample.tsx
  packages/docs-app/src/examples/table-examples/tableDollarExample.tsx
  packages/docs-app/src/examples/table-examples/tableEditableExample.tsx
  packages/docs-app/src/examples/table-examples/tableFormatsExample.tsx
  packages/docs-app/src/examples/table-examples/tableFreezingExample.tsx
  packages/docs-app/src/examples/table-examples/tableLoadingExample.tsx
  packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx
  packages/docs-app/src/examples/table-examples/tableSortableExample.tsx
  packages/table-dev-app/src/features.tsx
  packages/table-dev-app/src/mutableTable.tsx
  packages/table/src/docs/table-api.md
  packages/table/src/docs/table-features.md
  packages/table/src/docs/table.md
  packages/table/src/docs/table2.md
  packages/table/src/index.ts
  packages/table/src/table.tsx
  packages/table/src/table2Utils.ts
  packages/table/src/tableProps.ts
  packages/table/src/tableUtils.ts
  packages/table/test/columnTests.tsx
  packages/table/test/index.ts
  packages/table/test/loadingOptionsTests.tsx
  packages/table/test/mocks/table.tsx
  packages/table/test/tableTests.tsx
Labels: Type: breaking change, no changelog

#7335 chore: Rename v2 table files
  packages/table/src/table.tsx
  packages/table/src/tableBody.tsx
  packages/table/src/tableUtils.ts
  packages/table/test/tableBodyTests.tsx
Labels: no changelog

#7337 Fix type errors hidden by disabled `strictNullChecks` in `@blueprintjs/datetime` package
  packages/datetime/src/common/dateRangeSelectionStrategy.ts
  packages/datetime/src/common/dateUtils.ts
  packages/datetime/src/common/monthAndYear.ts
  packages/datetime/src/common/timeUnit.ts
  packages/datetime/src/components/time-picker/timePicker.tsx
  packages/datetime2/src/components/date-picker3/datePicker3.tsx
  packages/datetime2/src/components/date-range-picker3/contiguousDayRangePicker.tsx
  packages/datetime2/src/components/date-range-picker3/dateRangePicker3.tsx
  packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx
Labels: Package: datetime, no changelog

#7338 feat: Add locked document and code library icons
  packages/icons/changelog/@unreleased/pr-7338.v2.yml
  packages/icons/icons.json
  resources/icons/16px/document-code.svg
  resources/icons/16px/document-locked.svg
  resources/icons/20px/document-code.svg
  resources/icons/20px/document-locked.svg
Labels: Package: icons

#7340 Fix more errors hidden by disabled `strictNullChecks` in `@blueprintjs/datetime`
  packages/datetime/src/common/dateFormatProps.tsx
  packages/datetime/src/common/dateUtils.ts
  packages/datetime/test/common/dateUtilsTests.tsx
  packages/datetime/test/components/timePickerTests.tsx
  packages/test-commons/src/datetimeUtils.ts
Labels: no changelog

#7339 break(Overlay): Require OverlaysProvider to render
  packages/core/package.json
  packages/core/src/common/errors.ts
  packages/core/src/components/dialog/dialog.md
  packages/core/src/components/drawer/drawer.md
  packages/core/src/components/popover/popover.md
  packages/core/src/context/overlays/overlays-provider.md
  packages/core/src/context/overlays/overlaysProvider.tsx
  packages/core/src/hooks/overlays/useLegacyOverlayStack.ts
  packages/core/src/hooks/overlays/useOverlayStack.ts
  packages/core/test/hooks/useOverlayStackTests.tsx
  packages/select/src/components/omnibar/omnibar.md
  yarn.lock
Labels: Type: breaking change, no changelog

#7345 break(ContextMenu): Delete legacy target
  packages/core/src/index.ts
  packages/core/src/legacy/contextMenuLegacy.tsx
  packages/core/src/legacy/contextMenuTargetLegacy.tsx
Labels: Type: breaking change, no changelog

#7341 Add test for DateFormatProps
  packages/datetime/test/common/dateFormatPropsTests.ts
  packages/datetime/test/index.ts
Labels: Domain: testing, no changelog

#7346 [Datetime] Add `react-day-picker` v8 alias and port over common utils from `@blueprintjs/datetime2`
  packages/datetime/karma.conf.js
  packages/datetime/package.json
  packages/datetime/src/common/_react-day-picker-overrides.scss
  packages/datetime/src/common/classes.ts
  packages/datetime/src/common/dateFnsFormatUtils.ts
  packages/datetime/src/common/dateFnsLocaleProps.ts
  packages/datetime/src/common/dateFnsLocaleUtils.ts
  packages/datetime/src/common/dayPickerModifiers.ts
  packages/datetime/src/common/reactDayPickerProps.ts
  packages/datetime/src/common/reactDayPickerUtils.ts
  packages/datetime/src/common/useMonthSelectRightOffset.ts
  yarn.lock
Labels: Package: datetime, no changelog

#7347 break(Hotkeys): Delete legacy hotkeys target
  packages/core/src/components/hotkeys/hotkeys-target2.md
  packages/core/src/context/hotkeys/hotkeys-provider.md
  packages/core/src/docs/index.md
  packages/core/src/hooks/hotkeys/use-hotkeys.md
  packages/core/src/index.ts
  packages/core/src/legacy/hotkeys-legacy.md
  packages/core/src/legacy/hotkeysDialogLegacy.tsx
  packages/core/src/legacy/hotkeysEvents.ts
  packages/core/src/legacy/hotkeysTargetLegacy.tsx
  packages/core/src/legacy/legacy.md
  packages/core/src/legacy/legacyCommon.ts
  packages/docs-app/src/examples/core-examples/hotkeyPiano.tsx
  packages/docs-app/src/examples/core-examples/index.ts
Labels: Type: breaking change, no changelog

#7349 [Datetime] Port over `react-day-picker` and `date-fns` components from `@blueprintjs/datetime2`
  packages/datetime/package.json
  packages/datetime/src/components/date-picker3/datePicker3Context.tsx
  packages/datetime/src/components/date-picker3/datePicker3State.ts
  packages/datetime/src/components/dateFnsLocalizedComponent.tsx
  packages/datetime/src/components/react-day-picker/datePicker3Caption.tsx
  packages/datetime/src/components/react-day-picker/datePicker3Dropdown.tsx
  packages/datetime/src/components/react-day-picker/datePickerNavIcons.tsx
  yarn.lock
Labels: Package: datetime, no changelog

#7348 break(Hotkeys): Rename v2 components
  packages/core/src/common/errors.ts
  packages/core/src/components/components.md
  packages/core/src/components/hotkeys/hotkeys-target.md
  packages/core/src/components/hotkeys/hotkeysDialog.tsx
  packages/core/src/components/hotkeys/hotkeysTarget.tsx
  packages/core/src/components/hotkeys/index.ts
  packages/core/src/context/hotkeys/hotkeys-provider.md
  packages/core/src/context/hotkeys/hotkeysProvider.tsx
  packages/core/test/isotest.mjs
  packages/docs-app/src/components/navHeader.tsx
  packages/docs-app/src/examples/core-examples/hotkeysTargetExample.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/examples/select-examples/omnibarExample.tsx
  packages/docs-theme/src/components/documentation.tsx
  packages/table/src/cell/editableCell.tsx
  packages/table/src/table.tsx
Labels: Type: breaking change, no changelog

#7358 [Datetime] Wire up v3 components
  packages/datetime/karma.conf.js
  packages/datetime/src/blueprint-datetime.scss
  packages/datetime/src/index.ts
  packages/datetime/test/components/dateInputTests.tsx
  packages/datetime/test/components/datePickerTests.tsx
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/dateRangePickerTests.tsx
  packages/datetime/test/index.ts
Labels: Type: breaking change, Package: datetime, no changelog

#7359 [Datetime] Delete legacy datetime components
  packages/datetime/src/blueprint-datetime.scss
  packages/datetime/src/common/useMonthSelectRightOffset.ts
  packages/datetime/src/components/date-input/date-input.md
  packages/datetime/src/components/date-input/dateInput.tsx
  packages/datetime/src/components/date-input3/_dateinput.scss
  packages/datetime/src/components/date-input3/dateInput3.tsx
  packages/datetime/src/components/date-picker/datePicker.tsx
  packages/datetime/src/components/date-picker/datePickerCaption.tsx
  packages/datetime/src/components/date-picker/datePickerCore.tsx
  packages/datetime/src/components/date-picker/datePickerNavbar.tsx
  packages/datetime/src/components/date-picker/datepicker.md
  packages/datetime/src/components/date-picker3/_datepicker.scss
  packages/datetime/src/components/date-picker3/datePicker3.tsx
  packages/datetime/src/components/date-picker3/datePickerUtils.ts
  packages/datetime/src/components/date-range-input/date-range-input.md
  packages/datetime/src/components/date-range-input/dateRangeInput.tsx
  packages/datetime/src/components/date-range-input3/dateRangeInput3.tsx
  packages/datetime/src/components/date-range-picker/dateRangePicker.tsx
  packages/datetime/src/components/date-range-picker/daterangepicker.md
  packages/datetime/src/components/date-range-picker3/_daterangepicker.scss
  packages/datetime/src/components/date-range-picker3/dateRangePicker3.tsx
  packages/datetime/src/index.md
  packages/datetime/src/index.ts
  packages/datetime/test/common/dayPicker8TestUtils.ts
  packages/datetime/test/common/dayPickerTestUtils.ts
  packages/datetime/test/components/dateInputTests.tsx
  packages/datetime/test/components/datePicker3Tests.tsx
  packages/datetime/test/components/datePickerCaptionTests.tsx
  packages/datetime/test/components/datePickerTests.tsx
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/dateRangePicker3Tests.tsx
  packages/datetime/test/components/dateRangePickerTests.tsx
  packages/datetime/test/index.ts
Labels: Package: datetime, no changelog

#7361 Enable strictNullChecks in `@blueprintjs/datetime`
  packages/datetime/src/tsconfig.json
Labels: Package: datetime, no changelog

#7360 [Datetime] Upgrade `react-day-picker` at `v7.4.9` to `^8.10.0` and remove temporary v8 dependency
  .yarn/patches/react-day-picker-npm-7.4.9-8853eff118.patch
  packages/datetime/package.json
  packages/datetime/src/common/_react-day-picker-overrides.scss
  packages/datetime/src/common/classes.ts
  packages/datetime/src/common/datePickerBaseProps.ts
  packages/datetime/src/common/dayPickerModifiers.ts
  packages/datetime/src/common/reactDayPickerProps.ts
  packages/datetime/src/common/reactDayPickerUtils.ts
  packages/datetime/src/components/date-picker3/datePicker3.tsx
  packages/datetime/src/components/date-range-picker3/contiguousDayRangePicker.tsx
  packages/datetime/src/components/date-range-picker3/dateRangePicker3.tsx
  packages/datetime/src/components/date-range-picker3/dayRangePickerProps.ts
  packages/datetime/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx
  packages/datetime/src/components/react-day-picker/datePicker3Caption.tsx
  packages/datetime/src/components/react-day-picker/datePicker3Dropdown.tsx
  packages/datetime/src/components/react-day-picker/datePickerNavIcons.tsx
  packages/datetime/src/index.ts
  packages/datetime/test/components/datePicker3Tests.tsx
  packages/datetime/test/components/dateRangePicker3Tests.tsx
  packages/datetime2/src/index.ts
  yarn.lock
Labels: Type: breaking change, Package: datetime, dependencies, no changelog

#7362 Update `@blueprintjs/datetime` peerDependencies to match other packages
  packages/datetime/package.json
  yarn.lock
Labels: Type: breaking change, Package: datetime, dependencies, no changelog

#7364 break(Tabs): Delete deprecated TabsExpander aliases
  packages/core/src/components/index.ts
  packages/core/src/components/tabs/tabs.tsx
Labels: Type: breaking change, no changelog

#7366 [Datetime] Rename v3 components in `@blueprintjs/datetime`
  packages/datetime/src/blueprint-datetime.scss
  packages/datetime/src/common/classes.ts
  packages/datetime/src/common/reactDayPickerProps.ts
  packages/datetime/src/common/useMonthSelectRightOffset.ts
  packages/datetime/src/components/date-input/_dateinput.scss
  packages/datetime/src/components/date-input/date-input.md
  packages/datetime/src/components/date-input/dateInput.tsx
  packages/datetime/src/components/date-input/dateInputProps.ts
  packages/datetime/src/components/date-input/useDateFormatter.ts
  packages/datetime/src/components/date-input/useDateParser.ts
  packages/datetime/src/components/date-input3/dateInput3Props.ts
  packages/datetime/src/components/date-picker/_date-picker-caption.scss
  packages/datetime/src/components/date-picker/_date-picker.scss
  packages/datetime/src/components/date-picker/_datepicker.scss
  packages/datetime/src/components/date-picker/date-picker.md
  packages/datetime/src/components/date-picker/datePicker.tsx
  packages/datetime/src/components/date-picker/datePickerContext.tsx
  packages/datetime/src/components/date-picker/datePickerProps.ts
  packages/datetime/src/components/date-picker/datePickerState.ts
  packages/datetime/src/components/date-picker/datePickerUtils.ts
  packages/datetime/src/components/date-picker3/datePicker3Props.ts
  packages/datetime/src/components/date-range-input/date-range-input.md
  packages/datetime/src/components/date-range-input/dateRangeInput.tsx
  packages/datetime/src/components/date-range-input/dateRangeInputProps.ts
  packages/datetime/src/components/date-range-input/dateRangeInputState.ts
  packages/datetime/src/components/date-range-input/dateRangeInputUilts.ts
  packages/datetime/src/components/date-range-input3/dateRangeInput3Props.ts
  packages/datetime/src/components/date-range-picker/_date-range-picker.scss
  packages/datetime/src/components/date-range-picker/_daterangepicker.scss
  packages/datetime/src/components/date-range-picker/contiguousDayRangePicker.tsx
  packages/datetime/src/components/date-range-picker/date-range-picker.md
  packages/datetime/src/components/date-range-picker/dateRangePicker.tsx
  packages/datetime/src/components/date-range-picker/dateRangePickerProps.ts
  packages/datetime/src/components/date-range-picker/dateRangePickerState.ts
  packages/datetime/src/components/date-range-picker/dayRangePickerProps.ts
  packages/datetime/src/components/date-range-picker/nonContiguousDayRangePicker.tsx
  packages/datetime/src/components/date-range-picker3/dateRangePicker3Props.ts
  packages/datetime/src/components/dateFnsLocalizedComponent.tsx
  packages/datetime/src/components/react-day-picker/datePickerCaption.tsx
  packages/datetime/src/components/react-day-picker/datePickerDropdown.tsx
  packages/datetime/src/index.md
  packages/datetime/src/index.ts
  packages/datetime/test/components/dateInputTests.tsx
  packages/datetime/test/components/datePickerTests.tsx
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/dateRangePickerTests.tsx
  packages/datetime/test/index.ts
Labels: Package: datetime, no changelog

#7368 deprecation: Deprecate nested navbar components
  packages/core/src/components/navbar/navbar.md
  packages/core/src/components/navbar/navbar.tsx
  packages/table-dev-app/src/nav.tsx
Labels: no changelog

#7367 deprecation: Deprecate MultiSlider.Handle component
  packages/core/src/components/index.ts
  packages/core/src/components/slider/multiSlider.tsx
  packages/core/src/components/slider/rangeSlider.tsx
  packages/core/src/components/slider/slider.tsx
  packages/core/src/components/slider/sliders.md
  packages/core/test/isotest.mjs
  packages/core/test/slider/multiSliderTests.tsx
  packages/docs-app/src/examples/core-examples/multiSliderExample.tsx
Labels: no changelog

#7369 deprecation: Deprecate Tabs.Tab alias
  packages/core/src/components/tabs/tabs.tsx
Labels: no changelog

#7373 [eslint-plugin] Remove `no-deprecated-datetime-components` and update `no-deprecated-datetime2-components`
  packages/demo-app/src/examples/DatePickerExample.tsx
  packages/demo-app/src/examples/DateRangePickerExample.tsx
  packages/docs-app/src/examples/datetime2-examples/dateInput3Example.tsx
  packages/docs-app/src/examples/datetime2-examples/datePicker3Example.tsx
  packages/docs-app/src/examples/datetime2-examples/datePicker3LocalizedExample.tsx
  packages/docs-app/src/examples/datetime2-examples/datePicker3ModifierExample.tsx
  packages/docs-app/src/examples/datetime2-examples/dateRangeInput3Example.tsx
  packages/docs-app/src/examples/datetime2-examples/dateRangePicker3Example.tsx
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/index.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/index.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-components.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-datetime-components.ts
  packages/eslint-plugin/src/rules/no-deprecated-components/no-deprecated-datetime2-components.ts
  packages/eslint-plugin/test/no-deprecated-datetime-components.test.ts
  packages/eslint-plugin/test/no-deprecated-datetime2-components.test.ts
Labels: Domain: tooling, Type: breaking change, no changelog

#7374 break(Portal): Remove legacy context options
  packages/core/src/common/context.ts
  packages/core/src/common/errors.ts
  packages/core/src/common/utils/reactUtils.ts
  packages/core/src/components/portal/portal.md
  packages/core/src/components/portal/portal.tsx
Labels: Type: breaking change, no changelog

#7372 [docs] Merge and clean up datetime docs
  packages/datetime/README.md
  packages/datetime/src/common/datePickerBaseProps.ts
  packages/datetime/src/components/date-input/date-input.md
  packages/datetime/src/components/date-picker/date-picker.md
  packages/datetime/src/components/date-range-input/date-range-input.md
  packages/datetime/src/components/date-range-picker/date-range-picker.md
  packages/datetime/src/index.md
  packages/datetime2/src/components/date-input3/date-input3.md
  packages/datetime2/src/components/date-picker3/date-picker3.md
  packages/datetime2/src/components/date-range-input3/date-range-input3.md
  packages/datetime2/src/components/date-range-picker3/date-range-picker3.md
  packages/datetime2/src/index.md
  packages/demo-app/package.json
  packages/demo-app/src/index.scss
  packages/docs-app/package.json
  packages/docs-app/src/_nav.md
  packages/docs-app/src/blueprint.md
  packages/docs-app/src/examples/datetime-examples/common/dateFnsFormatSelect.tsx
  packages/docs-app/src/examples/datetime-examples/common/minMaxDateSelect.tsx
  packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
  packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
  packages/docs-app/src/examples/datetime-examples/datePickerLocalizedExample.tsx
  packages/docs-app/src/examples/datetime-examples/datePickerModifierExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
  packages/docs-app/src/examples/datetime-examples/index.ts
  packages/docs-app/src/examples/datetime2-examples/index.ts
  packages/docs-app/src/index.scss
  packages/docs-app/src/styles/_examples.scss
  packages/docs-app/src/tags/reactExamples.ts
  yarn.lock
Labels: Domain: documentation, Package: datetime, no changelog

#7378 docs: Fix missing hotkeys legacy reference
  packages/core/src/components/control-card/controlCard.tsx
  packages/core/src/hooks/hotkeys/use-hotkeys.md
Labels: no changelog

#7376 docs: Remove deprecated CSS API docs
  packages/core/src/components/breadcrumbs/_breadcrumbs.scss
  packages/core/src/components/button/_button-group.scss
  packages/core/src/components/button/_button.scss
  packages/core/src/components/button/button-group.md
  packages/core/src/components/button/buttons.md
  packages/core/src/components/callout/_callout.scss
  packages/core/src/components/callout/callout.md
  packages/core/src/components/card/_card.scss
  packages/core/src/components/card/card.md
  packages/core/src/components/dialog/_dialog.scss
  packages/core/src/components/dialog/dialog.md
  packages/core/src/components/forms/_control-group.scss
  packages/core/src/components/forms/_controls.scss
  packages/core/src/components/forms/_file-input.scss
  packages/core/src/components/forms/_form-group.scss
  packages/core/src/components/forms/_input-group.scss
  packages/core/src/components/forms/_input.scss
  packages/core/src/components/forms/_label.scss
  packages/core/src/components/forms/checkbox.md
  packages/core/src/components/forms/control-group.md
  packages/core/src/components/forms/file-input.md
  packages/core/src/components/forms/form-group.md
  packages/core/src/components/forms/input-group.md
  packages/core/src/components/forms/label.md
  packages/core/src/components/forms/radio.md
  packages/core/src/components/forms/switch.md
  packages/core/src/components/forms/text-area.md
  packages/core/src/components/html-select/_html-select.scss
  packages/core/src/components/html-select/html-select.md
  packages/core/src/components/html-table/_html-table.scss
  packages/core/src/components/html-table/html-table.md
  packages/core/src/components/menu/_menu.scss
  packages/core/src/components/menu/menu.md
  packages/core/src/components/navbar/_navbar.scss
  packages/core/src/components/navbar/navbar.md
  packages/core/src/components/non-ideal-state/_non-ideal-state.scss
  packages/core/src/components/non-ideal-state/non-ideal-state.md
  packages/core/src/components/progress-bar/_progress-bar.scss
  packages/core/src/components/progress-bar/progress-bar.md
  packages/core/src/components/tabs/_tabs.scss
  packages/core/src/components/tabs/tabs.md
  packages/core/src/components/tag/_tag.scss
  packages/core/src/components/tag/tag.md
  packages/core/src/components/tree/_tree.scss
  packages/core/src/components/tree/tree.md
  packages/docs-app/src/examples/core-examples/navbarExample.tsx
Labels: no changelog

#7377 [docs] Update datetime examples
  packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
  packages/docs-app/src/examples/datetime-examples/datePickerExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangeInputExample.tsx
  packages/docs-app/src/examples/datetime-examples/dateRangePickerExample.tsx
  packages/docs-app/src/examples/datetime-examples/timePickerExample.tsx
  packages/docs-app/src/examples/datetime-examples/timezoneSelectExample.tsx
Labels: Domain: documentation, no changelog

#7379 Feat(icon):gift box icon
  packages/icons/icons.json
  resources/icons/16px/gift-box.svg
  resources/icons/20px/gift-box.svg
Labels: Package: icons

#7383 [Datetime] Reexport `datetime2` components from `datetime`
  packages/datetime/src/index.ts
  packages/datetime2/README.md
  packages/datetime2/karma.conf.js
  packages/datetime2/package.json
  packages/datetime2/src/classes.ts
  packages/datetime2/src/common/dateFnsFormatUtils.ts
  packages/datetime2/src/common/dateFnsLocaleProps.ts
  packages/datetime2/src/common/dateFnsLocaleUtils.ts
  packages/datetime2/src/common/dayPickerModifiers.ts
  packages/datetime2/src/common/reactDayPickerProps.ts
  packages/datetime2/src/common/reactDayPickerUtils.ts
  packages/datetime2/src/common/useMonthSelectRightOffset.ts
  packages/datetime2/src/components/date-input3/dateInput3.tsx
  packages/datetime2/src/components/date-input3/dateInput3Props.ts
  packages/datetime2/src/components/date-input3/useDateFormatter.ts
  packages/datetime2/src/components/date-input3/useDateParser.ts
  packages/datetime2/src/components/date-picker3/datePicker3.tsx
  packages/datetime2/src/components/date-picker3/datePicker3Context.tsx
  packages/datetime2/src/components/date-picker3/datePicker3Props.ts
  packages/datetime2/src/components/date-picker3/datePicker3State.ts
  packages/datetime2/src/components/date-range-input3/dateRangeInput3.tsx
  packages/datetime2/src/components/date-range-input3/dateRangeInput3Props.ts
  packages/datetime2/src/components/date-range-input3/dateRangeInput3State.ts
  packages/datetime2/src/components/date-range-input3/dateRangeInputUilts.ts
  packages/datetime2/src/components/date-range-picker3/contiguousDayRangePicker.tsx
  packages/datetime2/src/components/date-range-picker3/dateRangePicker3.tsx
  packages/datetime2/src/components/date-range-picker3/dateRangePicker3Props.ts
  packages/datetime2/src/components/date-range-picker3/dateRangePicker3State.ts
  packages/datetime2/src/components/date-range-picker3/dayRangePickerProps.ts
  packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx
  packages/datetime2/src/components/dateFnsLocalizedComponent.tsx
  packages/datetime2/src/components/react-day-picker/datePicker3Caption.tsx
  packages/datetime2/src/components/react-day-picker/datePicker3Dropdown.tsx
  packages/datetime2/src/components/react-day-picker/datePickerNavIcons.tsx
  packages/datetime2/src/index.ts
  packages/datetime2/test/common/dayPickerTestUtils.ts
  packages/datetime2/test/common/loadDateFnsLocaleFake.ts
  packages/datetime2/test/components/dateInput3Tests.tsx
  packages/datetime2/test/components/datePicker3Tests.tsx
  packages/datetime2/test/components/dateRangeInput3Tests.tsx
  packages/datetime2/test/components/dateRangePicker3Tests.tsx
  packages/datetime2/test/index.ts
  packages/datetime2/test/isotest.mjs
  yarn.lock
Labels: Package: datetime, no changelog

#7386 Revert Overlays breaking changes
  packages/core/karma.conf.js
  packages/core/package.json
  packages/core/src/common/errors.ts
  packages/core/src/components/components.md
  packages/core/src/components/dialog/dialog.md
  packages/core/src/components/dialog/dialog.tsx
  packages/core/src/components/drawer/drawer.md
  packages/core/src/components/drawer/drawer.tsx
  packages/core/src/components/index.ts
  packages/core/src/components/overlay/overlay.md
  packages/core/src/components/overlay/overlay.tsx
  packages/core/src/components/overlay/overlayProps.ts
  packages/core/src/components/overlay/overlayUtils.ts
  packages/core/src/components/overlay2/overlay2.md
  packages/core/src/components/overlay2/overlay2.tsx
  packages/core/src/components/overlay2/overlayInstance.ts
  packages/core/src/components/popover/popover.md
  packages/core/src/components/popover/popover.tsx
  packages/core/src/components/portal/portal.md
  packages/core/src/components/toast/overlayToaster.tsx
  packages/core/src/components/toast/overlayToasterProps.ts
  packages/core/src/components/toast/toast.md
  packages/core/src/components/toast/toast.tsx
  packages/core/src/context/overlays/overlays-provider.md
  packages/core/src/context/overlays/overlaysProvider.tsx
  packages/core/src/docs/variables.md
  packages/core/src/hooks/overlays/use-overlay-stack.md
  packages/core/src/hooks/overlays/useLegacyOverlayStack.ts
  packages/core/src/hooks/overlays/useOverlayStack.ts
  packages/core/test/dialog/dialogTests.tsx
  packages/core/test/hooks/useOverlayStackTests.tsx
  packages/core/test/index.ts
  packages/core/test/isotest.mjs
  packages/core/test/overlay/overlayTests.tsx
  packages/core/test/overlay2/overlay2-test-debugging.scss
  packages/core/test/overlay2/overlay2Tests.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/tooltip/tooltipTests.tsx
  packages/docs-app/src/examples/core-examples/index.ts
  packages/docs-app/src/examples/core-examples/overlay2Example.tsx
  packages/docs-app/src/examples/core-examples/overlayExample.tsx
  packages/docs-app/src/styles/_examples.scss
  packages/select/src/components/omnibar/omnibar.md
  packages/select/src/components/omnibar/omnibar.tsx
  yarn.lock
Labels: no changelog

#7385 [Datetime] Swap `useLayoutEffect` for `useIsomorphicLayoutEffect` in `useMonthSelectRightOffset`
  packages/datetime/src/common/useMonthSelectRightOffset.ts
Labels: Package: datetime, no changelog

#7388 [Datetime] Port `dateInput2MigrationUtils` from `datetime2` to `datetime`
  .circleci/config.yml
  packages/datetime/karma.conf.js
  packages/datetime/src/dateInput2MigrationUtils.ts
  packages/datetime/src/index.ts
  packages/datetime/test/dateInput2MigrationUtilsTests.tsx
  packages/datetime/test/index.ts
  packages/datetime2/karma.conf.js
  packages/datetime2/package.json
  packages/datetime2/src/index.ts
  packages/datetime2/test/index.ts
  packages/datetime2/test/tsconfig.json
  yarn.lock
Labels: Package: datetime, no changelog

#7393 break(Toaster): Remove deprecated static create method
  packages/core/src/components/index.ts
  packages/core/src/components/toast/toaster.ts
  packages/core/test/index.ts
  packages/core/test/toast/toasterTests.tsx
Labels: Type: breaking change, no changelog

#7394 break(Toast): Delete Toast component
  packages/core/src/components/index.ts
  packages/core/src/components/toast/overlayToaster.tsx
  packages/core/src/components/toast/toast.tsx
  packages/core/test/index.ts
  packages/core/test/toast/toastTests.tsx
Labels: Type: breaking change, no changelog

#7397 [datetime2] Add back `date-fns` dependency required by `react-day-picker`
  packages/datetime2/package.json
  yarn.lock
Labels: Package: datetime, no changelog

#7398 Feat(icon): Sweep icon
  packages/icons/changelog/@unreleased/pr-7398.v2.yml
  packages/icons/icons.json
  resources/icons/16px/sweep.svg
  resources/icons/20px/sweep.svg
Labels: Package: icons

#7375 [Datetime] Update `DatePickerShortcutMenu` to a functional component
  packages/datetime/src/components/date-picker/datePicker.tsx
  packages/datetime/src/components/date-range-picker/dateRangePicker.tsx
  packages/datetime/src/components/shortcuts/shortcuts.tsx
  packages/datetime/test/components/dateRangePickerTests.tsx
Labels: Package: datetime, no changelog

#7390 break(OverlayToaster): Use React 18 createRoot for rendering via createAsync
  packages/core/src/components/toast/overlayToaster.tsx
  packages/core/test/toast/overlayToasterTests.tsx
Labels: Type: breaking change, no changelog

#7391 feat(ContextMenu): Introduce new API for imperative rendering
  packages/core/src/common/utils/mountOptions.ts
  packages/core/src/components/context-menu/context-menu-popover.md
  packages/core/src/components/context-menu/contextMenuSingleton.tsx
  packages/core/src/components/index.ts
Labels: no changelog

#7400 Cherry pick #7336: test: use testing-library waitFor instead of arbitrary wait times
  packages/core/test/dialog/dialogTests.tsx
  packages/core/test/forms/asyncControllableInputTests.tsx
  packages/core/test/overlay/overlayTests.tsx
  packages/core/test/overlay2/overlay2Tests.tsx
  packages/core/test/resize-sensor/resizeSensorTests.tsx
  packages/core/test/tabs/tabsTests.tsx
  packages/core/test/tag-input/tagInputTests.tsx
  packages/core/test/tag/compoundTagTests.tsx
  packages/core/test/tag/tagTests.tsx
  packages/core/test/toast/overlayToasterTests.tsx
  packages/core/test/toast/toastTests.tsx
  packages/core/test/tree/treeTests.tsx
Labels: no changelog

#7402 Cherry-pick #7387 and #7391
  packages/core/src/common/utils/mountOptions.ts
  packages/core/src/components/context-menu/context-menu-popover.md
  packages/core/src/components/context-menu/contextMenuSingleton.tsx
  packages/core/src/components/index.ts
  packages/eslint-plugin/src/tsconfig.json
  packages/eslint-plugin/test/tsconfig.json
Labels: no changelog

#7403 Cherry pick #7343: test: replace deprecated ReactDOM functions
  packages/core/test/alert/alertTests.tsx
  packages/core/test/breadcrumbs/breadcrumbsTests.tsx
  packages/core/test/callout/calloutTests.tsx
  packages/core/test/context-menu/contextMenuSingletonTests.tsx
  packages/core/test/context-menu/contextMenuTests.tsx
  packages/core/test/control-card/controlCardTests.tsx
  packages/core/test/controls/numericInputTests.tsx
  packages/core/test/drawer/drawerTests.tsx
  packages/core/test/entity-title/entityTitleTests.tsx
  packages/core/test/forms/textAreaTests.tsx
  packages/core/test/menu/menuItemTests.tsx
  packages/core/test/multistep-dialog/multistepDialogTests.tsx
  packages/core/test/overflow-list/overflowListTests.tsx
  packages/core/test/overlay/overlayTests.tsx
  packages/core/test/overlay2/overlay2Tests.tsx
  packages/core/test/panel-stack/panelStackTests.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/resize-sensor/resizeSensorTests.tsx
  packages/core/test/section/sectionTests.tsx
  packages/core/test/segmented-control/segmentedControlTests.tsx
  packages/core/test/slider/handleTests.tsx
  packages/core/test/slider/multiSliderTests.tsx
  packages/core/test/slider/rangeSliderTests.tsx
  packages/core/test/slider/sliderTests.tsx
  packages/core/test/tabs/tabsTests.tsx
  packages/core/test/text/textTests.tsx
  packages/core/test/toast/overlayToasterTests.tsx
  packages/core/test/tree/treeTests.tsx
  packages/datetime/test/components/dateInputTests.tsx
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/timePickerTests.tsx
  packages/select/test/multiSelectTests.tsx
  packages/select/test/selectTests.tsx
  packages/select/test/suggestTests.tsx
  packages/table/test/cellTests.tsx
  packages/table/test/columnHeaderCellTests.tsx
  packages/table/test/common/internal/scrollUtilsTests.tsx
  packages/table/test/formats/jsonFormatTests.tsx
  packages/table/test/formats/truncatedFormatTests.tsx
  packages/table/test/guidesTests.tsx
  packages/table/test/harness.ts
  packages/table/test/locatorTests.tsx
  packages/table/test/menusTests.tsx
  packages/table/test/quadrants/tableQuadrantStackTests.tsx
  packages/table/test/reorderableTests.tsx
  packages/table/test/resizableTests.tsx
  packages/table/test/rowHeaderCellTests.tsx
  packages/table/test/selectableTests.tsx
  packages/table/test/selectionTests.tsx
  packages/table/test/tableTests.tsx
Labels: no changelog

#7407 Fix Table row reordering example
  packages/docs-app/src/examples/table-examples/tableReorderableExample.tsx
  packages/table/src/docs/table-features.md
Labels: Domain: documentation, no changelog

#7412 Fix extra newline in table docs
  packages/table/src/docs/table-features.md
Labels: merge when ready

#7404 break(ContextMenuPopover): Use React18 to render imperative context menus
  packages/core/src/common/utils/mountOptions.ts
  packages/core/src/components/context-menu/context-menu-popover.md
  packages/core/src/components/context-menu/contextMenuSingleton.tsx
Labels: Type: breaking change, no changelog

#7409 break(OverlayToaster): Remove synchronous API
  packages/core/src/common/errors.ts
  packages/core/src/components/toast/overlayToaster.tsx
  packages/core/src/components/toast/toast.md
  packages/core/test/toast/overlayToasterTests.tsx
  packages/docs-app/src/examples/core-examples/alertExample.tsx
  packages/docs-app/src/examples/core-examples/toastCreateAsyncExample.tsx
  packages/docs-app/src/examples/select-examples/omnibarExample.tsx
Labels: Type: breaking change, no changelog

#7417 chore: Remove react-uid in favor of React.useId
  packages/core/package.json
  packages/core/src/components/overlay2/overlay2.tsx
  packages/core/src/hooks/overlays/use-overlay-stack.md
  packages/core/test/hooks/useOverlayStackTests.tsx
  yarn.lock
Labels: no changelog

#7410 break(Portal): Remove PortalLegacyContext type
  packages/core/src/components/index.ts
  packages/core/src/components/portal/portal.tsx
  packages/core/test/portal/portalTests.tsx
Labels: Type: breaking change, no changelog

#7415 Remove new tags from docs
  packages/core/src/components/card-list/card-list.md
  packages/core/src/components/control-card/control-card.md
  packages/core/src/components/entity-title/entity-title.md
  packages/core/src/components/overlay2/overlay2.md
  packages/core/src/components/section/section.md
  packages/core/src/components/segmented-control/segmented-control.md
  packages/core/src/components/tag/compound-tag.md
  packages/core/src/context/blueprint-provider.md
  packages/core/src/context/overlays/overlays-provider.md
  packages/core/src/context/portal/portal-provider.md
  packages/icons/src/loading-icons.md
Labels: no changelog

#7413 break: Update component display name prefix
  packages/core/src/common/props.ts
  packages/icons/scripts/iconComponent.tsx.hbs
  packages/icons/src/svgIconContainer.tsx
Labels: Type: breaking change, no changelog

#7411 break: Update namespace to bp6
  packages/core/src/common/_variables.scss
  packages/core/src/common/classes.ts
  packages/eslint-plugin/README.md
  packages/eslint-plugin/src/rules/classes-constants.ts
  packages/icons/scripts/common.mjs
  packages/icons/src/classes.ts
  packages/landing-app/src/index.html
  packages/stylelint-plugin/src/rules/no-prefix-literal.ts
Labels: Type: breaking change, no changelog

#7406 [popover2] Remove Popover2 Package
  packages/docs-app/src/components/navIcons.tsx
  packages/docs-app/src/styles/_nav.scss
  packages/popover2/.npmignore
  packages/popover2/LICENSE
  packages/popover2/README.md
  packages/popover2/changelog/@unreleased/.gitkeep
  packages/popover2/package.json
  packages/popover2/src/blueprint-popover2.scss
  packages/popover2/src/classes.ts
  packages/popover2/src/index.ts
  packages/popover2/src/popover2.tsx
  packages/popover2/src/tsconfig.json
  yarn.lock
Labels: no changelog, Package: popover2

#7414 break(Icon, SVGIconContainer): Update return types for React 18
  packages/core/src/components/icon/icon.tsx
  packages/icons/src/svgIconContainer.tsx
Labels: Type: breaking change, no changelog

#7422 [datetime] Merge legacy and v3 datetime props
  packages/datetime/src/common/dateFormatProps.tsx
  packages/datetime/src/common/datePickerBaseProps.ts
  packages/datetime/src/components/date-input/dateInputProps.ts
  packages/datetime/src/components/date-picker/datePickerProps.ts
  packages/datetime/src/components/date-range-input/dateRangeInputProps.ts
  packages/datetime/src/components/date-range-picker/dateRangePickerProps.ts
Labels: Package: datetime, no changelog

#7421 break: Drop React 16 and 17 as peer dependencies
  packages/core/package.json
  packages/datetime/package.json
  packages/datetime2/package.json
  packages/docs-theme/package.json
  packages/icons/package.json
  packages/select/package.json
  packages/table/package.json
  yarn.lock
Labels: Type: breaking change, no changelog
