Repository palantir/blueprint, pull requests merged in 2025-01, with the labels that each got.

#7131 Remove reference to old Cobalt colours in docs
  packages/docs-app/changelog/@unreleased/pr-7131.v2.yml
  packages/docs-app/src/components/colorSchemes.tsx
Labels: Domain: documentation

#6960 fix(timezoneSelect): a11y aria-label
  packages/datetime/src/components/timezone-select/timezoneSelect.tsx
Labels: Domain: accessibility

#7148 Wrap tests in TestUtils.act(...)
  packages/core/test/controls/numericInputTests.tsx
  packages/core/test/editable-text/editableTextTests.tsx
  packages/core/test/multistep-dialog/multistepDialogTests.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/tabs/tabsTests.tsx
  packages/core/test/tag-input/tagInputTests.tsx
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/timezoneSelectTests.tsx
  packages/datetime2/test/components/dateRangeInput3Tests.tsx
  packages/select/test/multiSelectTests.tsx
  packages/select/test/queryListTests.tsx
  packages/select/test/selectTests.tsx
  packages/select/test/suggestTests.tsx
  packages/table/test/editableCell2Tests.tsx
  packages/table/test/editableCellTests.tsx
  packages/table/test/table2Tests.tsx
  packages/table/test/tableTests.tsx
Labels: Domain: testing

#7156 chore: Remove no-submodule-imports rule
  packages/core/src/hooks/overlays/useLegacyOverlayStack.ts
  packages/core/test/icon/iconTests.tsx
  packages/datetime/test/index.ts
  packages/datetime2/test/components/dateInput3Tests.tsx
  packages/datetime2/test/index.ts
  packages/docs-app/src/examples/datetime-examples/timePickerExample.tsx
  packages/eslint-config/tslint.json
  packages/landing-app/src/svgs/index.ts
  packages/select/test/index.ts
Labels: no changelog

#7164 chore: Remove remaining tslint references
  packages/core/src/components/html/html.md
  packages/core/src/docs/classes.md
  packages/docs-app/src/examples/core-examples/popoverDismissExample.tsx
  packages/docs-app/src/examples/core-examples/popoverInteractionKindExample.tsx
  packages/docs-app/src/examples/core-examples/popoverMinimalExample.tsx
  packages/docs-app/src/examples/core-examples/popoverPortalExample.tsx
  packages/docs-app/src/examples/core-examples/popoverSizingExample.tsx
  packages/docs-app/src/examples/core-examples/toastExample.tsx
  packages/docs-app/src/examples/table-examples/tableSortableExample.tsx
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/tslint.json
  packages/table-dev-app/src/mutableTable.tsx
  packages/table-dev-app/src/sparseGridMutableStore.ts
  packages/table/src/common/rect.ts
  yarn.lock
Labels: no changelog

#7158 Docs: Update examples that reference ReactDOM.render
  packages/core/src/components/portal/portal.md
  packages/core/src/context/blueprint-provider.md
  packages/core/src/context/hotkeys/hotkeys-provider.md
  packages/core/src/context/overlays/overlays-provider.md
  packages/core/src/context/portal/portal-provider.md
  packages/docs-app/src/getting-started.md
  packages/icons/src/loading-icons.md
  packages/select/src/components/select/select-component.md
  packages/table/src/docs/table2.md
Labels: Domain: documentation

#7169 Skip "respects blueprintPortalClassName on legacy context" test
  packages/core/test/portal/portalTests.tsx
Labels: Domain: testing

#7171 Skip datetime component tests failing in React 18
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime2/test/components/dateRangeInput3Tests.tsx
Labels: Domain: testing

#7174 Patch react-day-picker@7.4.9 in datetime devDependencies
  .yarn/patches/react-day-picker-npm-7.4.9-8853eff118.patch
  packages/datetime/package.json
  yarn.lock
Labels: dependencies

#7142 React 18 Upgrade
  package.json
  packages/core/package.json
  packages/core/test/controls/numericInputTests.tsx
  packages/core/test/editable-text/editableTextTests.tsx
  packages/core/test/multistep-dialog/multistepDialogTests.tsx
  packages/core/test/overlay/overlayTests.tsx
  packages/core/test/popover/popoverTests.tsx
  packages/core/test/tabs/tabsTests.tsx
  packages/core/test/tag-input/tagInputTests.tsx
  packages/datetime/package.json
  packages/datetime/test/components/dateRangeInputTests.tsx
  packages/datetime/test/components/timezoneSelectTests.tsx
  packages/datetime2/package.json
  packages/datetime2/test/components/dateRangeInput3Tests.tsx
  packages/demo-app/package.json
  packages/demo-app/src/index.tsx
  packages/docs-app/package.json
  packages/docs-app/src/examples/core-examples/toastCreateAsyncExample.tsx
  packages/docs-app/src/index.tsx
  packages/docs-theme/package.json
  packages/icons/package.json
  packages/landing-app/package.json
  packages/popover2/package.json
  packages/select/package.json
  packages/select/test/multiSelectTests.tsx
  packages/select/test/queryListTests.tsx
  packages/select/test/selectTests.tsx
  packages/select/test/suggestTests.tsx
  packages/table-dev-app/package.json
  packages/table-dev-app/src/features.tsx
  packages/table-dev-app/src/index.tsx
  packages/table/package.json
  packages/table/test/editableCell2Tests.tsx
  packages/table/test/editableCellTests.tsx
  packages/table/test/table2Tests.tsx
  packages/table/test/tableTests.tsx
  packages/test-commons/bootstrap.mjs
  packages/test-commons/package.json
  yarn.lock
Labels: dependencies
