Repository palantir/blueprint, pull requests merged in 2025-04, with the labels that each got.

#7333 Custom attributes for <EditableText /> underlying textarea
  packages/core/src/common/props.ts
  packages/core/src/components/editable-text/editableText.tsx
  packages/core/test/editable-text/editableTextTests.tsx
Labels: Package: core, no changelog

#7382 test(Popover): waitFor instead of setTimeout
  packages/core/test/popover/popoverTests.tsx
Labels: Domain: testing, no changelog

#7424 [datetime] Consolidate styles between legacy and v3 components
  packages/datetime/src/blueprint-datetime.scss
  packages/datetime/src/common/classes.ts
  packages/datetime/src/common/datePickerBaseProps.ts
  packages/datetime/src/components/date-input/_date-input.scss
  packages/datetime/src/components/date-picker/_date-picker-caption.scss
  packages/datetime/src/components/date-picker/_date-picker.scss
  packages/datetime/src/components/date-picker/_datepicker.scss
  packages/datetime/src/components/date-range-picker/_date-range-picker.scss
  packages/datetime/src/components/date-range-picker/_daterangepicker.scss
  packages/datetime/src/components/time-picker/_time-picker.scss
Labels: Package: datetime, no changelog

#7425 [core]: Remove deprecated `Classes.SELECT` class from CSS API
  packages/core/src/common/classes.ts
  packages/core/src/components/html-select/_html-select.scss
Labels: Type: breaking change, no changelog

#7408 Remove UMD bundles from library packages
  packages/core/package.json
  packages/core/webpack.config.mjs
  packages/datetime/package.json
  packages/datetime/webpack.config.mjs
  packages/docs-app/src/getting-started.md
  packages/docs-theme/package.json
  packages/docs-theme/webpack.config.mjs
  packages/icons/package.json
  packages/icons/scripts/webpack.config.mjs
  packages/icons/webpack.config.mjs
  packages/select/package.json
  packages/select/webpack.config.mjs
  packages/table/package.json
  packages/table/webpack.config.mjs
  packages/webpack-build-scripts/externals.mjs
  packages/webpack-build-scripts/index.mjs
Labels: Domain: tooling, Type: breaking change, no changelog

#7435 Add icon support to Segment Control options
  packages/core/src/components/segmented-control/segmentedControl.tsx
  packages/core/test/segmented-control/segmentedControlTests.tsx
  packages/docs-app/src/examples/core-examples/segmentedControlExample.tsx
Labels: Package: core, no changelog

#7434 Target `es2019` in `tsconfig.web.json`
  config/tsconfig.web.json
Labels: no changelog
