Repository palantir/blueprint, pull requests merged in 2025-02, with the labels that each got.

#7225 Feat(Icon) - Phone search
  packages/icons/icons.json
  resources/icons/16px/phone-search.svg
  resources/icons/20px/phone-search.svg
Labels: Package: icons

#7207 [docs] Update Tag component examples
  packages/docs-app/src/examples/core-examples/compoundTagExample.tsx
  packages/docs-app/src/examples/core-examples/tagExample.tsx
  packages/docs-app/src/examples/core-examples/tagInputExample.tsx
Labels: Domain: documentation

#7209 [docs] Update input examples
  packages/docs-app/src/examples/core-examples/controlGroupExample.tsx
  packages/docs-app/src/examples/core-examples/editableTextExample.tsx
  packages/docs-app/src/examples/core-examples/fileInputExample.tsx
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/searchInputExample.tsx
  packages/docs-app/src/examples/core-examples/textAreaExample.tsx
  packages/docs-app/src/examples/core-examples/textExample.tsx
Labels: Domain: documentation

#7144 fix(Section): make collapsible keyboard accessible
  packages/core/src/components/section/section.tsx
Labels: no changelog

#7206 fix(MultiStepDialog): active step text contrast (a11y)
  packages/core/src/components/dialog/_multistep-dialog.scss
Labels: no changelog

#7230 fix(CompoundTag): Right icon alignment
  packages/core/src/components/tag/_compound-tag.scss
Labels: no changelog

#7210 [docs] Update Dialog examples
  packages/docs-app/src/examples/core-examples/dialogExample.tsx
  packages/docs-app/src/examples/core-examples/multistepDialogExample.tsx
Labels: Domain: documentation

#7233 fix(DateRangeInput3): Reset shortcut selection on selection
  packages/datetime2/src/components/date-range-input3/dateRangeInput3.tsx
Labels: no changelog

#7245 fix(Icons): Rename icons for consistency
  packages/icons/icons.json
  resources/icons/16px/announcement.svg
  resources/icons/16px/notifications-add.svg
  resources/icons/20px/announcement.svg
  resources/icons/20px/notifications-add.svg
Labels: Package: icons, no changelog

#7240 Skip flaky tests
  packages/core/test/popover/popoverTests.tsx
  packages/datetime2/test/components/dateRangeInput3Tests.tsx
Labels: Domain: testing, no changelog

#7221 [docs] Update Menu examples
  packages/docs-app/src/examples/core-examples/contextMenuExample.tsx
  packages/docs-app/src/examples/core-examples/dropdownMenuExample.tsx
Labels: Domain: documentation

#7220 [docs] Update Icon examples
  packages/docs-app/src/examples/core-examples/iconExample.tsx
  packages/docs-app/src/examples/core-examples/iconGeneratedComponentExample.tsx
Labels: Domain: documentation

#7219 [docs] Update Tabs Example
  packages/docs-app/src/examples/core-examples/tabsExample.tsx
Labels: Domain: documentation

#7218 [docs] Update Navbar Example
  packages/docs-app/src/examples/core-examples/navbarExample.tsx
Labels: Domain: documentation

#7259 [chore] Remove underscore prefix from memo/forwardRef components
  packages/core/src/components/context-menu/contextMenuPopover.tsx
  packages/core/src/components/forms/asyncControllableTextArea.tsx
  packages/datetime/src/components/date-input/dateInput.tsx
  packages/datetime2/src/components/date-input3/dateInput3.tsx
Labels: no changelog

#7197 Add `variant` prop to Button and ButtonGroup
  packages/core/karma.conf.js
  packages/core/src/common/buttonVariant.ts
  packages/core/src/common/classes.ts
  packages/core/src/common/errors.ts
  packages/core/src/common/index.ts
  packages/core/src/common/props.ts
  packages/core/src/components/button/button-group.md
  packages/core/src/components/button/buttonGroup.tsx
  packages/core/src/components/button/buttonProps.ts
  packages/core/src/components/button/buttons.md
  packages/core/src/components/button/buttons.tsx
  packages/core/src/components/dialog/dialog.tsx
  packages/core/src/components/drawer/drawer.tsx
  packages/core/src/components/panel-stack/panelView.tsx
  packages/core/src/components/panel-stack2/panelView2.tsx
  packages/core/src/components/segmented-control/segmentedControl.tsx
  packages/core/src/components/toast/toast.tsx
  packages/core/src/components/toast/toast2.tsx
  packages/core/src/docs/classes.md
  packages/core/test/controls/numericInputTests.tsx
  packages/datetime/src/components/date-picker/datePicker.tsx
  packages/datetime/src/components/date-picker/datePickerNavbar.tsx
  packages/datetime2/src/components/date-picker3/datePicker3.tsx
  packages/datetime2/src/components/react-day-picker/datePicker3Caption.tsx
  packages/demo-app/src/examples/ButtonExample.tsx
  packages/demo-app/src/examples/NonIdealStateExample.tsx
  packages/docs-app/src/components/blueprintDocs.tsx
  packages/docs-app/src/examples/core-examples/buttonExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
  packages/docs-app/src/examples/core-examples/buttonPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/cardListPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/common/variantSelect.tsx
  packages/docs-app/src/examples/core-examples/dividerPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/navbarExample.tsx
  packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
  packages/docs-app/src/examples/core-examples/popoverExample.tsx
  packages/docs-app/src/examples/core-examples/sectionExample.tsx
  packages/docs-app/src/examples/core-examples/tagInputExample.tsx
  packages/docs-app/src/styles/_examples.scss
  packages/docs-theme/src/tags/reactExample.tsx
  packages/select/src/components/multi-select/multiSelect.tsx
  packages/select/src/components/select/select.tsx
  packages/table-dev-app/src/nav.tsx
Labels: Domain: API, Package: core, no changelog

#7262 [chore] Remove unused eslint-disable directives
  packages/docs-app/src/examples/core-examples/overlayExample.tsx
  packages/docs-app/src/examples/core-examples/panelStackExample.tsx
  packages/docs-app/src/examples/datetime-examples/common/dateFnsDateFormatPropsSelect.tsx
Labels: no changelog

#7226 Add `size` prop to Button and ButtonGroup
  packages/core/src/common/classes.ts
  packages/core/src/common/errors.ts
  packages/core/src/common/index.ts
  packages/core/src/common/size.ts
  packages/core/src/components/button/button-group.md
  packages/core/src/components/button/buttonGroup.tsx
  packages/core/src/components/button/buttonProps.ts
  packages/core/src/components/button/buttons.md
  packages/core/src/components/button/buttons.tsx
  packages/core/src/components/panel-stack/panelView.tsx
  packages/core/src/components/panel-stack2/panelView2.tsx
  packages/docs-app/src/examples/core-examples/buttonExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
  packages/docs-app/src/examples/core-examples/buttonPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/cardListPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/common/legacySizeSelect.tsx
  packages/docs-app/src/examples/core-examples/common/sizeSelect.tsx
  packages/docs-app/src/examples/core-examples/menuExample.tsx
  packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx
  packages/docs-app/src/examples/core-examples/segmentedControlExample.tsx
  packages/docs-app/src/styles/_examples.scss
Labels: Domain: API, Package: core, no changelog

#7228 Add `size` prop to more components
  packages/core/src/components/forms/fileInput.tsx
  packages/core/src/components/forms/inputGroup.tsx
  packages/core/src/components/forms/numericInput.tsx
  packages/core/src/components/forms/textArea.tsx
  packages/core/src/components/menu/menu.tsx
  packages/core/src/components/segmented-control/segmentedControl.tsx
  packages/core/test/forms/fileInputTests.tsx
  packages/docs-app/src/components/icons.tsx
  packages/docs-app/src/examples/core-examples/common/alignmentSelect.tsx
  packages/docs-app/src/examples/core-examples/common/booleanOrUndefinedSelect.tsx
  packages/docs-app/src/examples/core-examples/common/layoutSelect.tsx
  packages/docs-app/src/examples/core-examples/common/legacySizeSelect.tsx
  packages/docs-app/src/examples/core-examples/common/sizeSelect.tsx
  packages/docs-app/src/examples/core-examples/common/textAlignmentSelect.tsx
  packages/docs-app/src/examples/core-examples/drawerExample.tsx
  packages/docs-app/src/examples/core-examples/fileInputExample.tsx
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/menuExample.tsx
  packages/docs-app/src/examples/core-examples/menuItemExample.tsx
  packages/docs-app/src/examples/core-examples/multistepDialogExample.tsx
  packages/docs-app/src/examples/core-examples/nonIdealStateExample.tsx
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
  packages/docs-app/src/examples/core-examples/searchInputExample.tsx
  packages/docs-app/src/examples/core-examples/segmentedControlExample.tsx
  packages/docs-app/src/examples/core-examples/textAreaExample.tsx
  packages/select/src/components/omnibar/omnibar.tsx
Labels: Domain: API, Package: core, no changelog

#7234 Add `size` prop to `large` variant components
  packages/core/src/common/index.ts
  packages/core/src/common/size.ts
  packages/core/src/components/control-card/controlCard.tsx
  packages/core/src/components/forms/controlProps.ts
  packages/core/src/components/forms/controls.tsx
  packages/core/src/components/tabs/tabs.tsx
  packages/core/src/components/tag-input/tagInput.tsx
  packages/core/src/components/tag/compoundTag.tsx
  packages/core/src/components/tag/tag.tsx
  packages/core/src/components/tag/tagRemoveButton.tsx
  packages/core/src/components/tag/tagSharedProps.ts
  packages/core/test/tabs/tabsTests.tsx
  packages/docs-app/src/examples/core-examples/checkboxExample.tsx
  packages/docs-app/src/examples/core-examples/compoundTagExample.tsx
  packages/docs-app/src/examples/core-examples/radioExample.tsx
  packages/docs-app/src/examples/core-examples/switchExample.tsx
  packages/docs-app/src/examples/core-examples/tabsExample.tsx
  packages/docs-app/src/examples/core-examples/tagExample.tsx
  packages/docs-app/src/examples/core-examples/tagInputExample.tsx
  packages/docs-app/src/examples/select-examples/multiSelectCustomTarget.tsx
Labels: Domain: API, Package: core, no changelog

#7255 Rename rightIcon to endIcon
  packages/core/src/common/props.ts
  packages/core/src/components/button/buttonGroup.tsx
  packages/core/src/components/button/buttonProps.ts
  packages/core/src/components/button/buttons.md
  packages/core/src/components/button/buttons.tsx
  packages/core/src/components/html-select/_common.scss
  packages/core/src/components/html-select/htmlSelect.tsx
  packages/core/src/components/menu/menu.md
  packages/core/src/components/tag/compoundTag.tsx
  packages/core/src/components/tag/tag.tsx
  packages/core/src/components/tag/tagSharedProps.ts
  packages/core/test/buttons/buttonTests.tsx
  packages/core/test/tag/compoundTagTests.tsx
  packages/core/test/tag/tagTests.tsx
  packages/datetime/src/components/date-input/dateInput.tsx
  packages/datetime/src/components/timezone-select/timezoneSelect.tsx
  packages/datetime/test/components/timezoneSelectTests.tsx
  packages/datetime2/src/components/date-input3/dateInput3.tsx
  packages/demo-app/src/examples/PopoverExample.tsx
  packages/docs-app/src/common/dateFnsLocaleSelect.tsx
  packages/docs-app/src/components/navHeader.tsx
  packages/docs-app/src/examples/core-examples/buttonExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupExamples.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/buttonGroupPopoverExample.tsx
  packages/docs-app/src/examples/core-examples/buttonPlaygroundExample.tsx
  packages/docs-app/src/examples/core-examples/common/iconSelect.tsx
  packages/docs-app/src/examples/core-examples/compoundTagExample.tsx
  packages/docs-app/src/examples/core-examples/dropdownMenuExample.tsx
  packages/docs-app/src/examples/core-examples/inputGroupExample.tsx
  packages/docs-app/src/examples/core-examples/overlay2Example.tsx
  packages/docs-app/src/examples/core-examples/overlayExample.tsx
  packages/docs-app/src/examples/core-examples/popoverDismissExample.tsx
  packages/docs-app/src/examples/core-examples/popoverExample.tsx
  packages/docs-app/src/examples/core-examples/tagExample.tsx
  packages/select/src/__examples__/filmSelect.tsx
  packages/select/src/components/select/select-component.md
Labels: Domain: API, Package: core, no changelog

#7217 [docs] Update NumericInput examples
  packages/docs-app/src/examples/core-examples/numericInputBasicExample.tsx
  packages/docs-app/src/examples/core-examples/numericInputExtendedExample.tsx
Labels: Domain: documentation

#7216 [docs] Update Section Example
  packages/docs-app/src/examples/core-examples/sectionExample.tsx
Labels: Domain: documentation

#7273 [docs] Fix horizontal overflow scrolling sidebar nav
  packages/core/src/docs/accessibility.md
  packages/core/src/docs/typography.md
  packages/docs-theme/src/styles/_layout.scss
  packages/docs-theme/src/styles/_variables.scss
Labels: Domain: documentation, no changelog

#7258 bugfix(Section): section header collapse button
  packages/core/src/common/classes.ts
  packages/core/src/components/section/_section.scss
  packages/core/src/components/section/section.tsx
Labels: no changelog

#7275 fix(Table): Fix not being able to use focus mode as a value
  packages/table/src/common/index.ts
  packages/table/src/index.ts
Labels: no changelog

#7277 fix(DayRangePicker3): Fixed being able to get out of bounds in non contiguous mode
  packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx
Labels: no changelog

#7256 fix(ToastCreateAsyncExample): must add props to `Example`
  README.md
  packages/core/webpack.config.mjs
  packages/datetime/webpack.config.mjs
  packages/docs-app/src/examples/core-examples/toastCreateAsyncExample.tsx
  packages/docs-theme/webpack.config.mjs
  packages/icons/scripts/webpack.config.mjs
  packages/icons/webpack.config.mjs
  packages/select/webpack.config.mjs
  packages/table/webpack.config.mjs
  packages/webpack-build-scripts/webpack.config.base.mjs
Labels: no changelog

#7280 Make ESLint plugin backwards compatible with v8
  packages/eslint-config/index.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/src/index.ts
  yarn.lock
Labels: no changelog

#7281 [Docs] Refactor Select Examples
  packages/docs-app/src/examples/select-examples/multiSelectExample.tsx
  packages/docs-app/src/examples/select-examples/omnibarExample.tsx
  packages/docs-app/src/examples/select-examples/selectExample.tsx
  packages/docs-app/src/examples/select-examples/suggestExample.tsx
Labels: Domain: documentation, no changelog

#7284 Add "inputSize" to InputGroup's filtered non-HTML props
  packages/core/src/components/forms/inputGroup.tsx
Labels: Type: bug, no changelog

#7285 Remove unwarranted size deprecation console warnings
  packages/core/src/common/errors.ts
Labels: Type: bug, no changelog
